(()=>{var io=Object.create;var xr=Object.defineProperty;var so=Object.getOwnPropertyDescriptor;var ao=Object.getOwnPropertyNames;var co=Object.getPrototypeOf,lo=Object.prototype.hasOwnProperty;var uo=(t,e)=>()=>(t&&(e=t(t=0)),e);var we=(t,e)=>()=>(e||t((e={exports:{}}).exports,e),e.exports);var fo=(t,e,r,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of ao(e))!lo.call(t,o)&&o!==r&&xr(t,o,{get:()=>e[o],enumerable:!(n=so(e,o))||n.enumerable});return t};var ze=(t,e,r)=>(r=t!=null?io(co(t)):{},fo(e||!t||!t.__esModule?xr(r,"default",{value:t,enumerable:!0}):r,t));var x,p=uo(()=>{x={env:{NODE_ENV:"production",LOG_LEVEL:"warn"},browser:!0,version:"",stdout:null,stderr:null,nextTick:function(t){var e=Array.prototype.slice.call(arguments,1);Promise.resolve().then(function(){t.apply(null,e)})}}});var fn=we(($a,un)=>{"use strict";p();function Wo(t){try{return JSON.stringify(t)}catch{return'"[Circular]"'}}un.exports=Ko;function Ko(t,e,r){var n=r&&r.stringify||Wo,o=1;if(typeof t=="object"&&t!==null){var i=e.length+o;if(i===1)return t;var s=new Array(i);s[0]=n(t);for(var a=1;a<i;a++)s[a]=n(e[a]);return s.join(" ")}if(typeof t!="string")return t;var l=e.length;if(l===0)return t;for(var c="",f=1-o,u=-1,m=t&&t.length||0,h=0;h<m;){if(t.charCodeAt(h)===37&&h+1<m){switch(u=u>-1?u:0,t.charCodeAt(h+1)){case 100:case 102:if(f>=l||e[f]==null)break;u<h&&(c+=t.slice(u,h)),c+=Number(e[f]),u=h+2,h++;break;case 105:if(f>=l||e[f]==null)break;u<h&&(c+=t.slice(u,h)),c+=Math.floor(Number(e[f])),u=h+2,h++;break;case 79:case 111:case 106:if(f>=l||e[f]===void 0)break;u<h&&(c+=t.slice(u,h));var B=typeof e[f];if(B==="string"){c+="'"+e[f]+"'",u=h+2,h++;break}if(B==="function"){c+=e[f].name||"<anonymous>",u=h+2,h++;break}c+=n(e[f]),u=h+2,h++;break;case 115:if(f>=l)break;u<h&&(c+=t.slice(u,h)),c+=String(e[f]),u=h+2,h++;break;case 37:u<h&&(c+=t.slice(u,h)),c+="%",u=h+2,h++,f--;break}++f}++h}return u===-1?t:(u<m&&(c+=t.slice(u)),c)}});var bn=we((Za,wt)=>{"use strict";p();var dn=fn();wt.exports=le;var Je=fi().console||{},Xo={mapHttpRequest:bt,mapHttpResponse:bt,wrapRequestSerializer:Qt,wrapResponseSerializer:Qt,wrapErrorSerializer:Qt,req:bt,res:bt,err:hn,errWithCause:hn};function pe(t,e){return t==="silent"?1/0:e.levels.values[t]}var rr=Symbol("pino.logFuncs"),er=Symbol("pino.hierarchy"),Jo={error:"log",fatal:"error",warn:"error",info:"log",debug:"log",trace:"log"};function pn(t,e){let r={logger:e,parent:t[er]};e[er]=r}function Qo(t,e,r){let n={};e.forEach(o=>{n[o]=r[o]?r[o]:Je[o]||Je[Jo[o]||"log"]||De}),t[rr]=n}function ei(t,e){return Array.isArray(t)?t.filter(function(n){return n!=="!stdSerializers.err"}):t===!0?Object.keys(e):!1}function le(t){t=t||{},t.browser=t.browser||{};let e=t.browser.transmit;if(e&&typeof e.send!="function")throw Error("pino: transmit option must have a send function");let r=t.browser.write||Je;t.browser.write&&(t.browser.asObject=!0);let n=t.serializers||{},o=ei(t.browser.serialize,n),i=t.browser.serialize;Array.isArray(t.browser.serialize)&&t.browser.serialize.indexOf("!stdSerializers.err")>-1&&(i=!1);let s=Object.keys(t.customLevels||{}),a=["error","fatal","warn","info","debug","trace"].concat(s);typeof r=="function"&&a.forEach(function(E){r[E]=r}),(t.enabled===!1||t.browser.disabled)&&(t.level="silent");let l=t.level||"info",c=Object.create(r);c.log||(c.log=De),Qo(c,a,r),pn({},c),Object.defineProperty(c,"levelVal",{get:u}),Object.defineProperty(c,"level",{get:m,set:h});let f={transmit:e,serialize:o,asObject:t.browser.asObject,asObjectBindingsOnly:t.browser.asObjectBindingsOnly,formatters:t.browser.formatters,reportCaller:t.browser.reportCaller,levels:a,timestamp:ci(t),messageKey:t.messageKey||"msg",onChild:t.onChild||De};c.levels=ti(t),c.level=l,c.isLevelEnabled=function(E){return this.levels.values[E]?this.levels.values[E]>=this.levels.values[this.level]:!1},c.setMaxListeners=c.getMaxListeners=c.emit=c.addListener=c.on=c.prependListener=c.once=c.prependOnceListener=c.removeListener=c.removeAllListeners=c.listeners=c.listenerCount=c.eventNames=c.write=c.flush=De,c.serializers=n,c._serialize=o,c._stdErrSerialize=i,c.child=function(...E){return B.call(this,f,...E)},e&&(c._logEvent=tr());function u(){return pe(this.level,this)}function m(){return this._level}function h(E){if(E!=="silent"&&!this.levels.values[E])throw Error("unknown level "+E);this._level=E,Be(this,f,c,"error"),Be(this,f,c,"fatal"),Be(this,f,c,"warn"),Be(this,f,c,"info"),Be(this,f,c,"debug"),Be(this,f,c,"trace"),s.forEach(L=>{Be(this,f,c,L)})}function B(E,L,F){if(!L)throw new Error("missing bindings for child Pino");F=F||{},o&&L.serializers&&(F.serializers=L.serializers);let ke=F.serializers;if(o&&ke){var re=Object.assign({},n,ke),ge=t.browser.serialize===!0?Object.keys(re):o;delete L.serializers,nr([L],ge,re,this._stdErrSerialize)}function be(Se){this._childLevel=(Se._childLevel|0)+1,this.bindings=L,re&&(this.serializers=re,this._serialize=ge),e&&(this._logEvent=tr([].concat(Se._logEvent.bindings,L)))}be.prototype=this;let ne=new be(this);return pn(this,ne),ne.child=function(...Se){return B.call(this,E,...Se)},ne.level=F.level||this.level,E.onChild(ne),ne}return c}function ti(t){let e=t.customLevels||{},r=Object.assign({},le.levels.values,e),n=Object.assign({},le.levels.labels,ri(e));return{values:r,labels:n}}function ri(t){let e={};return Object.keys(t).forEach(function(r){e[t[r]]=r}),e}le.levels={values:{fatal:60,error:50,warn:40,info:30,debug:20,trace:10},labels:{10:"trace",20:"debug",30:"info",40:"warn",50:"error",60:"fatal"}};le.stdSerializers=Xo;le.stdTimeFunctions=Object.assign({},{nullTime:mn,epochTime:gn,unixTime:li,isoTime:ui});function ni(t){let e=[];t.bindings&&e.push(t.bindings);let r=t[er];for(;r.parent;)r=r.parent,r.logger.bindings&&e.push(r.logger.bindings);return e.reverse()}function Be(t,e,r,n){if(Object.defineProperty(t,n,{value:pe(t.level,r)>pe(n,r)?De:r[rr][n],writable:!0,enumerable:!0,configurable:!0}),t[n]===De){if(!e.transmit)return;let i=e.transmit.level||t.level,s=pe(i,r);if(pe(n,r)<s)return}t[n]=ii(t,e,r,n);let o=ni(t);o.length!==0&&(t[n]=oi(o,t[n]))}function oi(t,e){return function(){return e.apply(this,[...t,...arguments])}}function ii(t,e,r,n){return(function(o){return function(){let s=e.timestamp(),a=new Array(arguments.length),l=Object.getPrototypeOf&&Object.getPrototypeOf(this)===Je?Je:this;for(var c=0;c<a.length;c++)a[c]=arguments[c];var f=!1;if(e.serialize&&(nr(a,this._serialize,this.serializers,this._stdErrSerialize),f=!0),e.asObject||e.formatters){let u=si(this,n,a,s,e);if(e.reportCaller&&u&&u.length>0&&u[0]&&typeof u[0]=="object")try{let m=yn();m&&(u[0].caller=m)}catch{}o.call(l,...u)}else{if(e.reportCaller)try{let u=yn();u&&a.push(u)}catch{}o.apply(l,a)}if(e.transmit){let u=e.transmit.level||t._level,m=pe(u,r),h=pe(n,r);if(h<m)return;ai(this,{ts:s,methodLevel:n,methodValue:h,transmitLevel:u,transmitValue:r.levels.values[e.transmit.level||t._level],send:e.transmit.send,val:pe(t._level,r)},a,f)}}})(t[rr][n])}function si(t,e,r,n,o){let{level:i,log:s=u=>u}=o.formatters||{},a=r.slice(),l=a[0],c={},f=(t._childLevel|0)+1;if(f<1&&(f=1),n&&(c.time=n),i){let u=i(e,t.levels.values[e]);Object.assign(c,u)}else c.level=t.levels.values[e];if(o.asObjectBindingsOnly){if(l!==null&&typeof l=="object")for(;f--&&typeof a[0]=="object";)Object.assign(c,a.shift());return[s(c),...a]}else{if(l!==null&&typeof l=="object"){for(;f--&&typeof a[0]=="object";)Object.assign(c,a.shift());l=a.length?dn(a.shift(),a):void 0}else typeof l=="string"&&(l=dn(a.shift(),a));return l!==void 0&&(c[o.messageKey]=l),[s(c)]}}function nr(t,e,r,n){for(let o in t)if(n&&t[o]instanceof Error)t[o]=le.stdSerializers.err(t[o]);else if(typeof t[o]=="object"&&!Array.isArray(t[o])&&e)for(let i in t[o])e.indexOf(i)>-1&&i in r&&(t[o][i]=r[i](t[o][i]))}function ai(t,e,r,n=!1){let o=e.send,i=e.ts,s=e.methodLevel,a=e.methodValue,l=e.val,c=t._logEvent.bindings;n||nr(r,t._serialize||Object.keys(t.serializers),t.serializers,t._stdErrSerialize===void 0?!0:t._stdErrSerialize),t._logEvent.ts=i,t._logEvent.messages=r.filter(function(f){return c.indexOf(f)===-1}),t._logEvent.level.label=s,t._logEvent.level.value=a,o(s,t._logEvent,l),t._logEvent=tr(c)}function tr(t){return{ts:0,messages:[],bindings:t||[],level:{label:"",value:0}}}function hn(t){let e={type:t.constructor.name,msg:t.message,stack:t.stack};for(let r in t)e[r]===void 0&&(e[r]=t[r]);return e}function ci(t){return typeof t.timestamp=="function"?t.timestamp:t.timestamp===!1?mn:gn}function bt(){return{}}function Qt(t){return t}function De(){}function mn(){return!1}function gn(){return Date.now()}function li(){return Math.round(Date.now()/1e3)}function ui(){return new Date(Date.now()).toISOString()}function fi(){function t(e){return typeof e<"u"&&e}try{return typeof globalThis<"u"||Object.defineProperty(Object.prototype,"globalThis",{get:function(){return delete Object.prototype.globalThis,this.globalThis=this},configurable:!0}),globalThis}catch{return t(self)||t(window)||t(this)||{}}}wt.exports.default=le;wt.exports.pino=le;function yn(){let t=new Error().stack;if(!t)return null;let e=t.split(`
`);for(let r=1;r<e.length;r++){let n=e[r].trim();if(/(^at\s+)?(createWrap|LOG|set\s*\(|asObject|Object\.apply|Function\.apply)/.test(n)||n.indexOf("browser.js")!==-1||n.indexOf("node:internal")!==-1||n.indexOf("node_modules")!==-1)continue;let o=n.match(/\((.*?):(\d+):(\d+)\)/);if(o||(o=n.match(/at\s+(.*?):(\d+):(\d+)/)),o){let i=o[1],s=o[2],a=o[3];return i+":"+s+":"+a}}return null}});var or=we((Qa,En)=>{p();En.exports={}});var In=we(Ve=>{"use strict";p();Object.defineProperty(Ve,"__esModule",{value:!0});Ve.bech32m=Ve.bech32=void 0;var xt="qpzry9x8gf2tvdw0s3jn54khce6mua7l",Bn={};for(let t=0;t<xt.length;t++){let e=xt.charAt(t);Bn[e]=t}function Pe(t){let e=t>>25;return(t&33554431)<<5^-(e>>0&1)&996825010^-(e>>1&1)&642813549^-(e>>2&1)&513874426^-(e>>3&1)&1027748829^-(e>>4&1)&705979059}function vn(t){let e=1;for(let r=0;r<t.length;++r){let n=t.charCodeAt(r);if(n<33||n>126)return"Invalid prefix ("+t+")";e=Pe(e)^n>>5}e=Pe(e);for(let r=0;r<t.length;++r){let n=t.charCodeAt(r);e=Pe(e)^n&31}return e}function ar(t,e,r,n){let o=0,i=0,s=(1<<r)-1,a=[];for(let l=0;l<t.length;++l)for(o=o<<e|t[l],i+=e;i>=r;)i-=r,a.push(o>>i&s);if(n)i>0&&a.push(o<<r-i&s);else{if(i>=e)return"Excess padding";if(o<<r-i&s)return"Non-zero padding"}return a}function vi(t){return ar(t,8,5,!0)}function Bi(t){let e=ar(t,5,8,!1);if(Array.isArray(e))return e}function Ai(t){let e=ar(t,5,8,!1);if(Array.isArray(e))return e;throw new Error(e)}function An(t){let e;t==="bech32"?e=1:e=734539939;function r(s,a,l){if(l=l||90,s.length+7+a.length>l)throw new TypeError("Exceeds length limit");s=s.toLowerCase();let c=vn(s);if(typeof c=="string")throw new Error(c);let f=s+"1";for(let u=0;u<a.length;++u){let m=a[u];if(m>>5!==0)throw new Error("Non 5-bit word");c=Pe(c)^m,f+=xt.charAt(m)}for(let u=0;u<6;++u)c=Pe(c);c^=e;for(let u=0;u<6;++u){let m=c>>(5-u)*5&31;f+=xt.charAt(m)}return f}function n(s,a){if(a=a||90,s.length<8)return s+" too short";if(s.length>a)return"Exceeds length limit";let l=s.toLowerCase(),c=s.toUpperCase();if(s!==l&&s!==c)return"Mixed-case string "+s;s=l;let f=s.lastIndexOf("1");if(f===-1)return"No separator character for "+s;if(f===0)return"Missing prefix for "+s;let u=s.slice(0,f),m=s.slice(f+1);if(m.length<6)return"Data too short";let h=vn(u);if(typeof h=="string")return h;let B=[];for(let E=0;E<m.length;++E){let L=m.charAt(E),F=Bn[L];if(F===void 0)return"Unknown character "+L;h=Pe(h)^F,!(E+6>=m.length)&&B.push(F)}return h!==e?"Invalid checksum for "+s:{prefix:u,words:B}}function o(s,a){let l=n(s,a);if(typeof l=="object")return l}function i(s,a){let l=n(s,a);if(typeof l=="object")return l;throw new Error(l)}return{decodeUnsafe:o,decode:i,encode:r,toWords:vi,fromWordsUnsafe:Bi,fromWords:Ai}}Ve.bech32=An("bech32");Ve.bech32m=An("bech32m")});var Tn=we(Et=>{"use strict";p();Et.byteLength=ki;Et.toByteArray=Ti;Et.fromByteArray=Ci;var ie=[],K=[],Ii=typeof Uint8Array<"u"?Uint8Array:Array,cr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";for(Ae=0,kn=cr.length;Ae<kn;++Ae)ie[Ae]=cr[Ae],K[cr.charCodeAt(Ae)]=Ae;var Ae,kn;K[45]=62;K[95]=63;function Sn(t){var e=t.length;if(e%4>0)throw new Error("Invalid string. Length must be a multiple of 4");var r=t.indexOf("=");r===-1&&(r=e);var n=r===e?0:4-r%4;return[r,n]}function ki(t){var e=Sn(t),r=e[0],n=e[1];return(r+n)*3/4-n}function Si(t,e,r){return(e+r)*3/4-r}function Ti(t){var e,r=Sn(t),n=r[0],o=r[1],i=new Ii(Si(t,n,o)),s=0,a=o>0?n-4:n,l;for(l=0;l<a;l+=4)e=K[t.charCodeAt(l)]<<18|K[t.charCodeAt(l+1)]<<12|K[t.charCodeAt(l+2)]<<6|K[t.charCodeAt(l+3)],i[s++]=e>>16&255,i[s++]=e>>8&255,i[s++]=e&255;return o===2&&(e=K[t.charCodeAt(l)]<<2|K[t.charCodeAt(l+1)]>>4,i[s++]=e&255),o===1&&(e=K[t.charCodeAt(l)]<<10|K[t.charCodeAt(l+1)]<<4|K[t.charCodeAt(l+2)]>>2,i[s++]=e>>8&255,i[s++]=e&255),i}function Ri(t){return ie[t>>18&63]+ie[t>>12&63]+ie[t>>6&63]+ie[t&63]}function _i(t,e,r){for(var n,o=[],i=e;i<r;i+=3)n=(t[i]<<16&16711680)+(t[i+1]<<8&65280)+(t[i+2]&255),o.push(Ri(n));return o.join("")}function Ci(t){for(var e,r=t.length,n=r%3,o=[],i=16383,s=0,a=r-n;s<a;s+=i)o.push(_i(t,s,s+i>a?a:s+i));return n===1?(e=t[r-1],o.push(ie[e>>2]+ie[e<<4&63]+"==")):n===2&&(e=(t[r-2]<<8)+t[r-1],o.push(ie[e>>10]+ie[e>>4&63]+ie[e<<2&63]+"=")),o.join("")}});var Rn=we(lr=>{p();lr.read=function(t,e,r,n,o){var i,s,a=o*8-n-1,l=(1<<a)-1,c=l>>1,f=-7,u=r?o-1:0,m=r?-1:1,h=t[e+u];for(u+=m,i=h&(1<<-f)-1,h>>=-f,f+=a;f>0;i=i*256+t[e+u],u+=m,f-=8);for(s=i&(1<<-f)-1,i>>=-f,f+=n;f>0;s=s*256+t[e+u],u+=m,f-=8);if(i===0)i=1-c;else{if(i===l)return s?NaN:(h?-1:1)*(1/0);s=s+Math.pow(2,n),i=i-c}return(h?-1:1)*s*Math.pow(2,i-n)};lr.write=function(t,e,r,n,o,i){var s,a,l,c=i*8-o-1,f=(1<<c)-1,u=f>>1,m=o===23?Math.pow(2,-24)-Math.pow(2,-77):0,h=n?0:i-1,B=n?1:-1,E=e<0||e===0&&1/e<0?1:0;for(e=Math.abs(e),isNaN(e)||e===1/0?(a=isNaN(e)?1:0,s=f):(s=Math.floor(Math.log(e)/Math.LN2),e*(l=Math.pow(2,-s))<1&&(s--,l*=2),s+u>=1?e+=m/l:e+=m*Math.pow(2,1-u),e*l>=2&&(s++,l/=2),s+u>=f?(a=0,s=f):s+u>=1?(a=(e*l-1)*Math.pow(2,o),s=s+u):(a=e*Math.pow(2,u-1)*Math.pow(2,o),s=0));o>=8;t[r+h]=a&255,h+=B,a/=256,o-=8);for(s=s<<o|a,c+=o;c>0;t[r+h]=s&255,h+=B,s/=256,c-=8);t[r+h-B]|=E*128}});var Gn=we(je=>{"use strict";p();var ur=Tn(),Me=Rn(),_n=typeof Symbol=="function"&&typeof Symbol.for=="function"?Symbol.for("nodejs.util.inspect.custom"):null;je.Buffer=d;je.SlowBuffer=Pi;je.INSPECT_MAX_BYTES=50;var vt=2147483647;je.kMaxLength=vt;d.TYPED_ARRAY_SUPPORT=Oi();!d.TYPED_ARRAY_SUPPORT&&typeof console<"u";function Oi(){try{let t=new Uint8Array(1),e={foo:function(){return 42}};return Object.setPrototypeOf(e,Uint8Array.prototype),Object.setPrototypeOf(t,e),t.foo()===42}catch{return!1}}Object.defineProperty(d.prototype,"parent",{enumerable:!0,get:function(){if(d.isBuffer(this))return this.buffer}});Object.defineProperty(d.prototype,"offset",{enumerable:!0,get:function(){if(d.isBuffer(this))return this.byteOffset}});function ue(t){if(t>vt)throw new RangeError('The value "'+t+'" is invalid for option "size"');let e=new Uint8Array(t);return Object.setPrototypeOf(e,d.prototype),e}function d(t,e,r){if(typeof t=="number"){if(typeof e=="string")throw new TypeError('The "string" argument must be of type string. Received type number');return hr(t)}return Ln(t,e,r)}d.poolSize=8192;function Ln(t,e,r){if(typeof t=="string")return Li(t,e);if(ArrayBuffer.isView(t))return Ni(t);if(t==null)throw new TypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type "+typeof t);if(se(t,ArrayBuffer)||t&&se(t.buffer,ArrayBuffer)||typeof SharedArrayBuffer<"u"&&(se(t,SharedArrayBuffer)||t&&se(t.buffer,SharedArrayBuffer)))return dr(t,e,r);if(typeof t=="number")throw new TypeError('The "value" argument must not be of type number. Received type number');let n=t.valueOf&&t.valueOf();if(n!=null&&n!==t)return d.from(n,e,r);let o=Di(t);if(o)return o;if(typeof Symbol<"u"&&Symbol.toPrimitive!=null&&typeof t[Symbol.toPrimitive]=="function")return d.from(t[Symbol.toPrimitive]("string"),e,r);throw new TypeError("The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type "+typeof t)}d.from=function(t,e,r){return Ln(t,e,r)};Object.setPrototypeOf(d.prototype,Uint8Array.prototype);Object.setPrototypeOf(d,Uint8Array);function Nn(t){if(typeof t!="number")throw new TypeError('"size" argument must be of type number');if(t<0)throw new RangeError('The value "'+t+'" is invalid for option "size"')}function Ui(t,e,r){return Nn(t),t<=0?ue(t):e!==void 0?typeof r=="string"?ue(t).fill(e,r):ue(t).fill(e):ue(t)}d.alloc=function(t,e,r){return Ui(t,e,r)};function hr(t){return Nn(t),ue(t<0?0:yr(t)|0)}d.allocUnsafe=function(t){return hr(t)};d.allocUnsafeSlow=function(t){return hr(t)};function Li(t,e){if((typeof e!="string"||e==="")&&(e="utf8"),!d.isEncoding(e))throw new TypeError("Unknown encoding: "+e);let r=Dn(t,e)|0,n=ue(r),o=n.write(t,e);return o!==r&&(n=n.slice(0,o)),n}function fr(t){let e=t.length<0?0:yr(t.length)|0,r=ue(e);for(let n=0;n<e;n+=1)r[n]=t[n]&255;return r}function Ni(t){if(se(t,Uint8Array)){let e=new Uint8Array(t);return dr(e.buffer,e.byteOffset,e.byteLength)}return fr(t)}function dr(t,e,r){if(e<0||t.byteLength<e)throw new RangeError('"offset" is outside of buffer bounds');if(t.byteLength<e+(r||0))throw new RangeError('"length" is outside of buffer bounds');let n;return e===void 0&&r===void 0?n=new Uint8Array(t):r===void 0?n=new Uint8Array(t,e):n=new Uint8Array(t,e,r),Object.setPrototypeOf(n,d.prototype),n}function Di(t){if(d.isBuffer(t)){let e=yr(t.length)|0,r=ue(e);return r.length===0||t.copy(r,0,0,e),r}if(t.length!==void 0)return typeof t.length!="number"||gr(t.length)?ue(0):fr(t);if(t.type==="Buffer"&&Array.isArray(t.data))return fr(t.data)}function yr(t){if(t>=vt)throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+vt.toString(16)+" bytes");return t|0}function Pi(t){return+t!=t&&(t=0),d.alloc(+t)}d.isBuffer=function(e){return e!=null&&e._isBuffer===!0&&e!==d.prototype};d.compare=function(e,r){if(se(e,Uint8Array)&&(e=d.from(e,e.offset,e.byteLength)),se(r,Uint8Array)&&(r=d.from(r,r.offset,r.byteLength)),!d.isBuffer(e)||!d.isBuffer(r))throw new TypeError('The "buf1", "buf2" arguments must be one of type Buffer or Uint8Array');if(e===r)return 0;let n=e.length,o=r.length;for(let i=0,s=Math.min(n,o);i<s;++i)if(e[i]!==r[i]){n=e[i],o=r[i];break}return n<o?-1:o<n?1:0};d.isEncoding=function(e){switch(String(e).toLowerCase()){case"hex":case"utf8":case"utf-8":case"ascii":case"latin1":case"binary":case"base64":case"ucs2":case"ucs-2":case"utf16le":case"utf-16le":return!0;default:return!1}};d.concat=function(e,r){if(!Array.isArray(e))throw new TypeError('"list" argument must be an Array of Buffers');if(e.length===0)return d.alloc(0);let n;if(r===void 0)for(r=0,n=0;n<e.length;++n)r+=e[n].length;let o=d.allocUnsafe(r),i=0;for(n=0;n<e.length;++n){let s=e[n];if(se(s,Uint8Array))i+s.length>o.length?(d.isBuffer(s)||(s=d.from(s)),s.copy(o,i)):Uint8Array.prototype.set.call(o,s,i);else if(d.isBuffer(s))s.copy(o,i);else throw new TypeError('"list" argument must be an Array of Buffers');i+=s.length}return o};function Dn(t,e){if(d.isBuffer(t))return t.length;if(ArrayBuffer.isView(t)||se(t,ArrayBuffer))return t.byteLength;if(typeof t!="string")throw new TypeError('The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type '+typeof t);let r=t.length,n=arguments.length>2&&arguments[2]===!0;if(!n&&r===0)return 0;let o=!1;for(;;)switch(e){case"ascii":case"latin1":case"binary":return r;case"utf8":case"utf-8":return pr(t).length;case"ucs2":case"ucs-2":case"utf16le":case"utf-16le":return r*2;case"hex":return r>>>1;case"base64":return $n(t).length;default:if(o)return n?-1:pr(t).length;e=(""+e).toLowerCase(),o=!0}}d.byteLength=Dn;function Vi(t,e,r){let n=!1;if((e===void 0||e<0)&&(e=0),e>this.length||((r===void 0||r>this.length)&&(r=this.length),r<=0)||(r>>>=0,e>>>=0,r<=e))return"";for(t||(t="utf8");;)switch(t){case"hex":return Yi(this,e,r);case"utf8":case"utf-8":return Vn(this,e,r);case"ascii":return Gi(this,e,r);case"latin1":case"binary":return Zi(this,e,r);case"base64":return zi(this,e,r);case"ucs2":case"ucs-2":case"utf16le":case"utf-16le":return Wi(this,e,r);default:if(n)throw new TypeError("Unknown encoding: "+t);t=(t+"").toLowerCase(),n=!0}}d.prototype._isBuffer=!0;function Ie(t,e,r){let n=t[e];t[e]=t[r],t[r]=n}d.prototype.swap16=function(){let e=this.length;if(e%2!==0)throw new RangeError("Buffer size must be a multiple of 16-bits");for(let r=0;r<e;r+=2)Ie(this,r,r+1);return this};d.prototype.swap32=function(){let e=this.length;if(e%4!==0)throw new RangeError("Buffer size must be a multiple of 32-bits");for(let r=0;r<e;r+=4)Ie(this,r,r+3),Ie(this,r+1,r+2);return this};d.prototype.swap64=function(){let e=this.length;if(e%8!==0)throw new RangeError("Buffer size must be a multiple of 64-bits");for(let r=0;r<e;r+=8)Ie(this,r,r+7),Ie(this,r+1,r+6),Ie(this,r+2,r+5),Ie(this,r+3,r+4);return this};d.prototype.toString=function(){let e=this.length;return e===0?"":arguments.length===0?Vn(this,0,e):Vi.apply(this,arguments)};d.prototype.toLocaleString=d.prototype.toString;d.prototype.equals=function(e){if(!d.isBuffer(e))throw new TypeError("Argument must be a Buffer");return this===e?!0:d.compare(this,e)===0};d.prototype.inspect=function(){let e="",r=je.INSPECT_MAX_BYTES;return e=this.toString("hex",0,r).replace(/(.{2})/g,"$1 ").trim(),this.length>r&&(e+=" ... "),"<Buffer "+e+">"};_n&&(d.prototype[_n]=d.prototype.inspect);d.prototype.compare=function(e,r,n,o,i){if(se(e,Uint8Array)&&(e=d.from(e,e.offset,e.byteLength)),!d.isBuffer(e))throw new TypeError('The "target" argument must be one of type Buffer or Uint8Array. Received type '+typeof e);if(r===void 0&&(r=0),n===void 0&&(n=e?e.length:0),o===void 0&&(o=0),i===void 0&&(i=this.length),r<0||n>e.length||o<0||i>this.length)throw new RangeError("out of range index");if(o>=i&&r>=n)return 0;if(o>=i)return-1;if(r>=n)return 1;if(r>>>=0,n>>>=0,o>>>=0,i>>>=0,this===e)return 0;let s=i-o,a=n-r,l=Math.min(s,a),c=this.slice(o,i),f=e.slice(r,n);for(let u=0;u<l;++u)if(c[u]!==f[u]){s=c[u],a=f[u];break}return s<a?-1:a<s?1:0};function Pn(t,e,r,n,o){if(t.length===0)return-1;if(typeof r=="string"?(n=r,r=0):r>2147483647?r=2147483647:r<-2147483648&&(r=-2147483648),r=+r,gr(r)&&(r=o?0:t.length-1),r<0&&(r=t.length+r),r>=t.length){if(o)return-1;r=t.length-1}else if(r<0)if(o)r=0;else return-1;if(typeof e=="string"&&(e=d.from(e,n)),d.isBuffer(e))return e.length===0?-1:Cn(t,e,r,n,o);if(typeof e=="number")return e=e&255,typeof Uint8Array.prototype.indexOf=="function"?o?Uint8Array.prototype.indexOf.call(t,e,r):Uint8Array.prototype.lastIndexOf.call(t,e,r):Cn(t,[e],r,n,o);throw new TypeError("val must be string, number or Buffer")}function Cn(t,e,r,n,o){let i=1,s=t.length,a=e.length;if(n!==void 0&&(n=String(n).toLowerCase(),n==="ucs2"||n==="ucs-2"||n==="utf16le"||n==="utf-16le")){if(t.length<2||e.length<2)return-1;i=2,s/=2,a/=2,r/=2}function l(f,u){return i===1?f[u]:f.readUInt16BE(u*i)}let c;if(o){let f=-1;for(c=r;c<s;c++)if(l(t,c)===l(e,f===-1?0:c-f)){if(f===-1&&(f=c),c-f+1===a)return f*i}else f!==-1&&(c-=c-f),f=-1}else for(r+a>s&&(r=s-a),c=r;c>=0;c--){let f=!0;for(let u=0;u<a;u++)if(l(t,c+u)!==l(e,u)){f=!1;break}if(f)return c}return-1}d.prototype.includes=function(e,r,n){return this.indexOf(e,r,n)!==-1};d.prototype.indexOf=function(e,r,n){return Pn(this,e,r,n,!0)};d.prototype.lastIndexOf=function(e,r,n){return Pn(this,e,r,n,!1)};function Hi(t,e,r,n){r=Number(r)||0;let o=t.length-r;n?(n=Number(n),n>o&&(n=o)):n=o;let i=e.length;n>i/2&&(n=i/2);let s;for(s=0;s<n;++s){let a=parseInt(e.substr(s*2,2),16);if(gr(a))return s;t[r+s]=a}return s}function Mi(t,e,r,n){return Bt(pr(e,t.length-r),t,r,n)}function Fi(t,e,r,n){return Bt(Qi(e),t,r,n)}function ji(t,e,r,n){return Bt($n(e),t,r,n)}function qi(t,e,r,n){return Bt(es(e,t.length-r),t,r,n)}d.prototype.write=function(e,r,n,o){if(r===void 0)o="utf8",n=this.length,r=0;else if(n===void 0&&typeof r=="string")o=r,n=this.length,r=0;else if(isFinite(r))r=r>>>0,isFinite(n)?(n=n>>>0,o===void 0&&(o="utf8")):(o=n,n=void 0);else throw new Error("Buffer.write(string, encoding, offset[, length]) is no longer supported");let i=this.length-r;if((n===void 0||n>i)&&(n=i),e.length>0&&(n<0||r<0)||r>this.length)throw new RangeError("Attempt to write outside buffer bounds");o||(o="utf8");let s=!1;for(;;)switch(o){case"hex":return Hi(this,e,r,n);case"utf8":case"utf-8":return Mi(this,e,r,n);case"ascii":case"latin1":case"binary":return Fi(this,e,r,n);case"base64":return ji(this,e,r,n);case"ucs2":case"ucs-2":case"utf16le":case"utf-16le":return qi(this,e,r,n);default:if(s)throw new TypeError("Unknown encoding: "+o);o=(""+o).toLowerCase(),s=!0}};d.prototype.toJSON=function(){return{type:"Buffer",data:Array.prototype.slice.call(this._arr||this,0)}};function zi(t,e,r){return e===0&&r===t.length?ur.fromByteArray(t):ur.fromByteArray(t.slice(e,r))}function Vn(t,e,r){r=Math.min(t.length,r);let n=[],o=e;for(;o<r;){let i=t[o],s=null,a=i>239?4:i>223?3:i>191?2:1;if(o+a<=r){let l,c,f,u;switch(a){case 1:i<128&&(s=i);break;case 2:l=t[o+1],(l&192)===128&&(u=(i&31)<<6|l&63,u>127&&(s=u));break;case 3:l=t[o+1],c=t[o+2],(l&192)===128&&(c&192)===128&&(u=(i&15)<<12|(l&63)<<6|c&63,u>2047&&(u<55296||u>57343)&&(s=u));break;case 4:l=t[o+1],c=t[o+2],f=t[o+3],(l&192)===128&&(c&192)===128&&(f&192)===128&&(u=(i&15)<<18|(l&63)<<12|(c&63)<<6|f&63,u>65535&&u<1114112&&(s=u))}}s===null?(s=65533,a=1):s>65535&&(s-=65536,n.push(s>>>10&1023|55296),s=56320|s&1023),n.push(s),o+=a}return $i(n)}var On=4096;function $i(t){let e=t.length;if(e<=On)return String.fromCharCode.apply(String,t);let r="",n=0;for(;n<e;)r+=String.fromCharCode.apply(String,t.slice(n,n+=On));return r}function Gi(t,e,r){let n="";r=Math.min(t.length,r);for(let o=e;o<r;++o)n+=String.fromCharCode(t[o]&127);return n}function Zi(t,e,r){let n="";r=Math.min(t.length,r);for(let o=e;o<r;++o)n+=String.fromCharCode(t[o]);return n}function Yi(t,e,r){let n=t.length;(!e||e<0)&&(e=0),(!r||r<0||r>n)&&(r=n);let o="";for(let i=e;i<r;++i)o+=ts[t[i]];return o}function Wi(t,e,r){let n=t.slice(e,r),o="";for(let i=0;i<n.length-1;i+=2)o+=String.fromCharCode(n[i]+n[i+1]*256);return o}d.prototype.slice=function(e,r){let n=this.length;e=~~e,r=r===void 0?n:~~r,e<0?(e+=n,e<0&&(e=0)):e>n&&(e=n),r<0?(r+=n,r<0&&(r=0)):r>n&&(r=n),r<e&&(r=e);let o=this.subarray(e,r);return Object.setPrototypeOf(o,d.prototype),o};function M(t,e,r){if(t%1!==0||t<0)throw new RangeError("offset is not uint");if(t+e>r)throw new RangeError("Trying to access beyond buffer length")}d.prototype.readUintLE=d.prototype.readUIntLE=function(e,r,n){e=e>>>0,r=r>>>0,n||M(e,r,this.length);let o=this[e],i=1,s=0;for(;++s<r&&(i*=256);)o+=this[e+s]*i;return o};d.prototype.readUintBE=d.prototype.readUIntBE=function(e,r,n){e=e>>>0,r=r>>>0,n||M(e,r,this.length);let o=this[e+--r],i=1;for(;r>0&&(i*=256);)o+=this[e+--r]*i;return o};d.prototype.readUint8=d.prototype.readUInt8=function(e,r){return e=e>>>0,r||M(e,1,this.length),this[e]};d.prototype.readUint16LE=d.prototype.readUInt16LE=function(e,r){return e=e>>>0,r||M(e,2,this.length),this[e]|this[e+1]<<8};d.prototype.readUint16BE=d.prototype.readUInt16BE=function(e,r){return e=e>>>0,r||M(e,2,this.length),this[e]<<8|this[e+1]};d.prototype.readUint32LE=d.prototype.readUInt32LE=function(e,r){return e=e>>>0,r||M(e,4,this.length),(this[e]|this[e+1]<<8|this[e+2]<<16)+this[e+3]*16777216};d.prototype.readUint32BE=d.prototype.readUInt32BE=function(e,r){return e=e>>>0,r||M(e,4,this.length),this[e]*16777216+(this[e+1]<<16|this[e+2]<<8|this[e+3])};d.prototype.readBigUInt64LE=ye(function(e){e=e>>>0,Fe(e,"offset");let r=this[e],n=this[e+7];(r===void 0||n===void 0)&&Qe(e,this.length-8);let o=r+this[++e]*2**8+this[++e]*2**16+this[++e]*2**24,i=this[++e]+this[++e]*2**8+this[++e]*2**16+n*2**24;return BigInt(o)+(BigInt(i)<<BigInt(32))});d.prototype.readBigUInt64BE=ye(function(e){e=e>>>0,Fe(e,"offset");let r=this[e],n=this[e+7];(r===void 0||n===void 0)&&Qe(e,this.length-8);let o=r*2**24+this[++e]*2**16+this[++e]*2**8+this[++e],i=this[++e]*2**24+this[++e]*2**16+this[++e]*2**8+n;return(BigInt(o)<<BigInt(32))+BigInt(i)});d.prototype.readIntLE=function(e,r,n){e=e>>>0,r=r>>>0,n||M(e,r,this.length);let o=this[e],i=1,s=0;for(;++s<r&&(i*=256);)o+=this[e+s]*i;return i*=128,o>=i&&(o-=Math.pow(2,8*r)),o};d.prototype.readIntBE=function(e,r,n){e=e>>>0,r=r>>>0,n||M(e,r,this.length);let o=r,i=1,s=this[e+--o];for(;o>0&&(i*=256);)s+=this[e+--o]*i;return i*=128,s>=i&&(s-=Math.pow(2,8*r)),s};d.prototype.readInt8=function(e,r){return e=e>>>0,r||M(e,1,this.length),this[e]&128?(255-this[e]+1)*-1:this[e]};d.prototype.readInt16LE=function(e,r){e=e>>>0,r||M(e,2,this.length);let n=this[e]|this[e+1]<<8;return n&32768?n|4294901760:n};d.prototype.readInt16BE=function(e,r){e=e>>>0,r||M(e,2,this.length);let n=this[e+1]|this[e]<<8;return n&32768?n|4294901760:n};d.prototype.readInt32LE=function(e,r){return e=e>>>0,r||M(e,4,this.length),this[e]|this[e+1]<<8|this[e+2]<<16|this[e+3]<<24};d.prototype.readInt32BE=function(e,r){return e=e>>>0,r||M(e,4,this.length),this[e]<<24|this[e+1]<<16|this[e+2]<<8|this[e+3]};d.prototype.readBigInt64LE=ye(function(e){e=e>>>0,Fe(e,"offset");let r=this[e],n=this[e+7];(r===void 0||n===void 0)&&Qe(e,this.length-8);let o=this[e+4]+this[e+5]*2**8+this[e+6]*2**16+(n<<24);return(BigInt(o)<<BigInt(32))+BigInt(r+this[++e]*2**8+this[++e]*2**16+this[++e]*2**24)});d.prototype.readBigInt64BE=ye(function(e){e=e>>>0,Fe(e,"offset");let r=this[e],n=this[e+7];(r===void 0||n===void 0)&&Qe(e,this.length-8);let o=(r<<24)+this[++e]*2**16+this[++e]*2**8+this[++e];return(BigInt(o)<<BigInt(32))+BigInt(this[++e]*2**24+this[++e]*2**16+this[++e]*2**8+n)});d.prototype.readFloatLE=function(e,r){return e=e>>>0,r||M(e,4,this.length),Me.read(this,e,!0,23,4)};d.prototype.readFloatBE=function(e,r){return e=e>>>0,r||M(e,4,this.length),Me.read(this,e,!1,23,4)};d.prototype.readDoubleLE=function(e,r){return e=e>>>0,r||M(e,8,this.length),Me.read(this,e,!0,52,8)};d.prototype.readDoubleBE=function(e,r){return e=e>>>0,r||M(e,8,this.length),Me.read(this,e,!1,52,8)};function $(t,e,r,n,o,i){if(!d.isBuffer(t))throw new TypeError('"buffer" argument must be a Buffer instance');if(e>o||e<i)throw new RangeError('"value" argument is out of bounds');if(r+n>t.length)throw new RangeError("Index out of range")}d.prototype.writeUintLE=d.prototype.writeUIntLE=function(e,r,n,o){if(e=+e,r=r>>>0,n=n>>>0,!o){let a=Math.pow(2,8*n)-1;$(this,e,r,n,a,0)}let i=1,s=0;for(this[r]=e&255;++s<n&&(i*=256);)this[r+s]=e/i&255;return r+n};d.prototype.writeUintBE=d.prototype.writeUIntBE=function(e,r,n,o){if(e=+e,r=r>>>0,n=n>>>0,!o){let a=Math.pow(2,8*n)-1;$(this,e,r,n,a,0)}let i=n-1,s=1;for(this[r+i]=e&255;--i>=0&&(s*=256);)this[r+i]=e/s&255;return r+n};d.prototype.writeUint8=d.prototype.writeUInt8=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,1,255,0),this[r]=e&255,r+1};d.prototype.writeUint16LE=d.prototype.writeUInt16LE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,2,65535,0),this[r]=e&255,this[r+1]=e>>>8,r+2};d.prototype.writeUint16BE=d.prototype.writeUInt16BE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,2,65535,0),this[r]=e>>>8,this[r+1]=e&255,r+2};d.prototype.writeUint32LE=d.prototype.writeUInt32LE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,4,4294967295,0),this[r+3]=e>>>24,this[r+2]=e>>>16,this[r+1]=e>>>8,this[r]=e&255,r+4};d.prototype.writeUint32BE=d.prototype.writeUInt32BE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,4,4294967295,0),this[r]=e>>>24,this[r+1]=e>>>16,this[r+2]=e>>>8,this[r+3]=e&255,r+4};function Hn(t,e,r,n,o){zn(e,n,o,t,r,7);let i=Number(e&BigInt(4294967295));t[r++]=i,i=i>>8,t[r++]=i,i=i>>8,t[r++]=i,i=i>>8,t[r++]=i;let s=Number(e>>BigInt(32)&BigInt(4294967295));return t[r++]=s,s=s>>8,t[r++]=s,s=s>>8,t[r++]=s,s=s>>8,t[r++]=s,r}function Mn(t,e,r,n,o){zn(e,n,o,t,r,7);let i=Number(e&BigInt(4294967295));t[r+7]=i,i=i>>8,t[r+6]=i,i=i>>8,t[r+5]=i,i=i>>8,t[r+4]=i;let s=Number(e>>BigInt(32)&BigInt(4294967295));return t[r+3]=s,s=s>>8,t[r+2]=s,s=s>>8,t[r+1]=s,s=s>>8,t[r]=s,r+8}d.prototype.writeBigUInt64LE=ye(function(e,r=0){return Hn(this,e,r,BigInt(0),BigInt("0xffffffffffffffff"))});d.prototype.writeBigUInt64BE=ye(function(e,r=0){return Mn(this,e,r,BigInt(0),BigInt("0xffffffffffffffff"))});d.prototype.writeIntLE=function(e,r,n,o){if(e=+e,r=r>>>0,!o){let l=Math.pow(2,8*n-1);$(this,e,r,n,l-1,-l)}let i=0,s=1,a=0;for(this[r]=e&255;++i<n&&(s*=256);)e<0&&a===0&&this[r+i-1]!==0&&(a=1),this[r+i]=(e/s>>0)-a&255;return r+n};d.prototype.writeIntBE=function(e,r,n,o){if(e=+e,r=r>>>0,!o){let l=Math.pow(2,8*n-1);$(this,e,r,n,l-1,-l)}let i=n-1,s=1,a=0;for(this[r+i]=e&255;--i>=0&&(s*=256);)e<0&&a===0&&this[r+i+1]!==0&&(a=1),this[r+i]=(e/s>>0)-a&255;return r+n};d.prototype.writeInt8=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,1,127,-128),e<0&&(e=255+e+1),this[r]=e&255,r+1};d.prototype.writeInt16LE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,2,32767,-32768),this[r]=e&255,this[r+1]=e>>>8,r+2};d.prototype.writeInt16BE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,2,32767,-32768),this[r]=e>>>8,this[r+1]=e&255,r+2};d.prototype.writeInt32LE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,4,2147483647,-2147483648),this[r]=e&255,this[r+1]=e>>>8,this[r+2]=e>>>16,this[r+3]=e>>>24,r+4};d.prototype.writeInt32BE=function(e,r,n){return e=+e,r=r>>>0,n||$(this,e,r,4,2147483647,-2147483648),e<0&&(e=4294967295+e+1),this[r]=e>>>24,this[r+1]=e>>>16,this[r+2]=e>>>8,this[r+3]=e&255,r+4};d.prototype.writeBigInt64LE=ye(function(e,r=0){return Hn(this,e,r,-BigInt("0x8000000000000000"),BigInt("0x7fffffffffffffff"))});d.prototype.writeBigInt64BE=ye(function(e,r=0){return Mn(this,e,r,-BigInt("0x8000000000000000"),BigInt("0x7fffffffffffffff"))});function Fn(t,e,r,n,o,i){if(r+n>t.length)throw new RangeError("Index out of range");if(r<0)throw new RangeError("Index out of range")}function jn(t,e,r,n,o){return e=+e,r=r>>>0,o||Fn(t,e,r,4,34028234663852886e22,-34028234663852886e22),Me.write(t,e,r,n,23,4),r+4}d.prototype.writeFloatLE=function(e,r,n){return jn(this,e,r,!0,n)};d.prototype.writeFloatBE=function(e,r,n){return jn(this,e,r,!1,n)};function qn(t,e,r,n,o){return e=+e,r=r>>>0,o||Fn(t,e,r,8,17976931348623157e292,-17976931348623157e292),Me.write(t,e,r,n,52,8),r+8}d.prototype.writeDoubleLE=function(e,r,n){return qn(this,e,r,!0,n)};d.prototype.writeDoubleBE=function(e,r,n){return qn(this,e,r,!1,n)};d.prototype.copy=function(e,r,n,o){if(!d.isBuffer(e))throw new TypeError("argument should be a Buffer");if(n||(n=0),!o&&o!==0&&(o=this.length),r>=e.length&&(r=e.length),r||(r=0),o>0&&o<n&&(o=n),o===n||e.length===0||this.length===0)return 0;if(r<0)throw new RangeError("targetStart out of bounds");if(n<0||n>=this.length)throw new RangeError("Index out of range");if(o<0)throw new RangeError("sourceEnd out of bounds");o>this.length&&(o=this.length),e.length-r<o-n&&(o=e.length-r+n);let i=o-n;return this===e&&typeof Uint8Array.prototype.copyWithin=="function"?this.copyWithin(r,n,o):Uint8Array.prototype.set.call(e,this.subarray(n,o),r),i};d.prototype.fill=function(e,r,n,o){if(typeof e=="string"){if(typeof r=="string"?(o=r,r=0,n=this.length):typeof n=="string"&&(o=n,n=this.length),o!==void 0&&typeof o!="string")throw new TypeError("encoding must be a string");if(typeof o=="string"&&!d.isEncoding(o))throw new TypeError("Unknown encoding: "+o);if(e.length===1){let s=e.charCodeAt(0);(o==="utf8"&&s<128||o==="latin1")&&(e=s)}}else typeof e=="number"?e=e&255:typeof e=="boolean"&&(e=Number(e));if(r<0||this.length<r||this.length<n)throw new RangeError("Out of range index");if(n<=r)return this;r=r>>>0,n=n===void 0?this.length:n>>>0,e||(e=0);let i;if(typeof e=="number")for(i=r;i<n;++i)this[i]=e;else{let s=d.isBuffer(e)?e:d.from(e,o),a=s.length;if(a===0)throw new TypeError('The value "'+e+'" is invalid for argument "value"');for(i=0;i<n-r;++i)this[i+r]=s[i%a]}return this};var He={};function mr(t,e,r){He[t]=class extends r{constructor(){super(),Object.defineProperty(this,"message",{value:e.apply(this,arguments),writable:!0,configurable:!0}),this.name=`${this.name} [${t}]`,this.stack,delete this.name}get code(){return t}set code(o){Object.defineProperty(this,"code",{configurable:!0,enumerable:!0,value:o,writable:!0})}toString(){return`${this.name} [${t}]: ${this.message}`}}}mr("ERR_BUFFER_OUT_OF_BOUNDS",function(t){return t?`${t} is outside of buffer bounds`:"Attempt to access memory outside buffer bounds"},RangeError);mr("ERR_INVALID_ARG_TYPE",function(t,e){return`The "${t}" argument must be of type number. Received type ${typeof e}`},TypeError);mr("ERR_OUT_OF_RANGE",function(t,e,r){let n=`The value of "${t}" is out of range.`,o=r;return Number.isInteger(r)&&Math.abs(r)>2**32?o=Un(String(r)):typeof r=="bigint"&&(o=String(r),(r>BigInt(2)**BigInt(32)||r<-(BigInt(2)**BigInt(32)))&&(o=Un(o)),o+="n"),n+=` It must be ${e}. Received ${o}`,n},RangeError);function Un(t){let e="",r=t.length,n=t[0]==="-"?1:0;for(;r>=n+4;r-=3)e=`_${t.slice(r-3,r)}${e}`;return`${t.slice(0,r)}${e}`}function Ki(t,e,r){Fe(e,"offset"),(t[e]===void 0||t[e+r]===void 0)&&Qe(e,t.length-(r+1))}function zn(t,e,r,n,o,i){if(t>r||t<e){let s=typeof e=="bigint"?"n":"",a;throw i>3?e===0||e===BigInt(0)?a=`>= 0${s} and < 2${s} ** ${(i+1)*8}${s}`:a=`>= -(2${s} ** ${(i+1)*8-1}${s}) and < 2 ** ${(i+1)*8-1}${s}`:a=`>= ${e}${s} and <= ${r}${s}`,new He.ERR_OUT_OF_RANGE("value",a,t)}Ki(n,o,i)}function Fe(t,e){if(typeof t!="number")throw new He.ERR_INVALID_ARG_TYPE(e,"number",t)}function Qe(t,e,r){throw Math.floor(t)!==t?(Fe(t,r),new He.ERR_OUT_OF_RANGE(r||"offset","an integer",t)):e<0?new He.ERR_BUFFER_OUT_OF_BOUNDS:new He.ERR_OUT_OF_RANGE(r||"offset",`>= ${r?1:0} and <= ${e}`,t)}var Xi=/[^+/0-9A-Za-z-_]/g;function Ji(t){if(t=t.split("=")[0],t=t.trim().replace(Xi,""),t.length<2)return"";for(;t.length%4!==0;)t=t+"=";return t}function pr(t,e){e=e||1/0;let r,n=t.length,o=null,i=[];for(let s=0;s<n;++s){if(r=t.charCodeAt(s),r>55295&&r<57344){if(!o){if(r>56319){(e-=3)>-1&&i.push(239,191,189);continue}else if(s+1===n){(e-=3)>-1&&i.push(239,191,189);continue}o=r;continue}if(r<56320){(e-=3)>-1&&i.push(239,191,189),o=r;continue}r=(o-55296<<10|r-56320)+65536}else o&&(e-=3)>-1&&i.push(239,191,189);if(o=null,r<128){if((e-=1)<0)break;i.push(r)}else if(r<2048){if((e-=2)<0)break;i.push(r>>6|192,r&63|128)}else if(r<65536){if((e-=3)<0)break;i.push(r>>12|224,r>>6&63|128,r&63|128)}else if(r<1114112){if((e-=4)<0)break;i.push(r>>18|240,r>>12&63|128,r>>6&63|128,r&63|128)}else throw new Error("Invalid code point")}return i}function Qi(t){let e=[];for(let r=0;r<t.length;++r)e.push(t.charCodeAt(r)&255);return e}function es(t,e){let r,n,o,i=[];for(let s=0;s<t.length&&!((e-=2)<0);++s)r=t.charCodeAt(s),n=r>>8,o=r%256,i.push(o),i.push(n);return i}function $n(t){return ur.toByteArray(Ji(t))}function Bt(t,e,r,n){let o;for(o=0;o<n&&!(o+r>=e.length||o>=t.length);++o)e[o+r]=t[o];return o}function se(t,e){return t instanceof e||t!=null&&t.constructor!=null&&t.constructor.name!=null&&t.constructor.name===e.name}function gr(t){return t!==t}var ts=(function(){let t="0123456789abcdef",e=new Array(256);for(let r=0;r<16;++r){let n=r*16;for(let o=0;o<16;++o)e[n+o]=t[r]+t[o]}return e})();function ye(t){return typeof BigInt>"u"?rs:t}function rs(){throw new Error("BigInt not supported")}});p();p();var g=typeof browser<"u"?browser:typeof chrome<"u"?chrome:null;if(!g)throw new Error("browser-polyfill: No extension API namespace found (neither browser nor chrome).");var P=typeof browser>"u"&&typeof chrome<"u";function V(t,e){return(...r)=>{try{let n=e.apply(t,r);if(n&&typeof n.then=="function")return n}catch{}return new Promise((n,o)=>{e.apply(t,[...r,(...i)=>{g.runtime&&g.runtime.lastError?o(new Error(g.runtime.lastError.message)):n(i.length<=1?i[0]:i)}])})}}var Z={};Z.runtime={sendMessage(...t){return P?V(g.runtime,g.runtime.sendMessage)(...t):g.runtime.sendMessage(...t)},onMessage:g.runtime.onMessage,getURL(t){return g.runtime.getURL(t)},openOptionsPage(){return P?V(g.runtime,g.runtime.openOptionsPage)():g.runtime.openOptionsPage()},get id(){return g.runtime.id}};Z.storage={local:{get(...t){return P?V(g.storage.local,g.storage.local.get)(...t):g.storage.local.get(...t)},set(...t){return P?V(g.storage.local,g.storage.local.set)(...t):g.storage.local.set(...t)},clear(...t){return P?V(g.storage.local,g.storage.local.clear)(...t):g.storage.local.clear(...t)},remove(...t){return P?V(g.storage.local,g.storage.local.remove)(...t):g.storage.local.remove(...t)}},sync:g.storage?.sync?{get(...t){return P?V(g.storage.sync,g.storage.sync.get)(...t):g.storage.sync.get(...t)},set(...t){return P?V(g.storage.sync,g.storage.sync.set)(...t):g.storage.sync.set(...t)},remove(...t){return P?V(g.storage.sync,g.storage.sync.remove)(...t):g.storage.sync.remove(...t)},clear(...t){return P?V(g.storage.sync,g.storage.sync.clear)(...t):g.storage.sync.clear(...t)},getBytesInUse(...t){return g.storage.sync.getBytesInUse?P?V(g.storage.sync,g.storage.sync.getBytesInUse)(...t):g.storage.sync.getBytesInUse(...t):Promise.resolve(0)}}:null,onChanged:g.storage?.onChanged||null};Z.tabs={create(...t){return P?V(g.tabs,g.tabs.create)(...t):g.tabs.create(...t)},query(...t){return P?V(g.tabs,g.tabs.query)(...t):g.tabs.query(...t)},remove(...t){return P?V(g.tabs,g.tabs.remove)(...t):g.tabs.remove(...t)},update(...t){return P?V(g.tabs,g.tabs.update)(...t):g.tabs.update(...t)},get(...t){return P?V(g.tabs,g.tabs.get)(...t):g.tabs.get(...t)},getCurrent(...t){return P?V(g.tabs,g.tabs.getCurrent)(...t):g.tabs.getCurrent(...t)},sendMessage(...t){return P?V(g.tabs,g.tabs.sendMessage)(...t):g.tabs.sendMessage(...t)}};Z.alarms=g.alarms?{create(...t){let e=g.alarms.create(...t);return e&&typeof e.then=="function"?e:Promise.resolve()},clear(...t){return P?V(g.alarms,g.alarms.clear)(...t):g.alarms.clear(...t)},onAlarm:g.alarms.onAlarm}:null;p();p();p();p();p();function It(t){return t instanceof Uint8Array||ArrayBuffer.isView(t)&&t.constructor.name==="Uint8Array"}function xe(t,e=""){if(!Number.isSafeInteger(t)||t<0){let r=e&&`"${e}" `;throw new Error(`${r}expected integer >= 0, got ${t}`)}}function D(t,e,r=""){let n=It(t),o=t?.length,i=e!==void 0;if(!n||i&&o!==e){let s=r&&`"${r}" `,a=i?` of length ${e}`:"",l=n?`length=${o}`:`type=${typeof t}`;throw new Error(s+"expected Uint8Array"+a+", got "+l)}return t}function kt(t,e=!0){if(t.destroyed)throw new Error("Hash instance has been destroyed");if(e&&t.finished)throw new Error("Hash#digest() has already been called")}function vr(t,e){D(t,void 0,"digestInto() output");let r=e.outputLen;if(t.length<r)throw new Error('"digestInto() output" expected to be of length >='+r)}function $e(...t){for(let e=0;e<t.length;e++)t[e].fill(0)}function et(t){return new DataView(t.buffer,t.byteOffset,t.byteLength)}function Q(t,e){return t<<32-e|t>>>e}var Br=typeof Uint8Array.from([]).toHex=="function"&&typeof Uint8Array.fromHex=="function",po=Array.from({length:256},(t,e)=>e.toString(16).padStart(2,"0"));function Re(t){if(D(t),Br)return t.toHex();let e="";for(let r=0;r<t.length;r++)e+=po[t[r]];return e}var ae={_0:48,_9:57,A:65,F:70,a:97,f:102};function Er(t){if(t>=ae._0&&t<=ae._9)return t-ae._0;if(t>=ae.A&&t<=ae.F)return t-(ae.A-10);if(t>=ae.a&&t<=ae.f)return t-(ae.a-10)}function Ge(t){if(typeof t!="string")throw new Error("hex string expected, got "+typeof t);if(Br)return Uint8Array.fromHex(t);let e=t.length,r=e/2;if(e%2)throw new Error("hex string expected, got unpadded hex of length "+e);let n=new Uint8Array(r);for(let o=0,i=0;o<r;o++,i+=2){let s=Er(t.charCodeAt(i)),a=Er(t.charCodeAt(i+1));if(s===void 0||a===void 0){let l=t[i]+t[i+1];throw new Error('hex string expected, got non-hex character "'+l+'" at index '+i)}n[o]=s*16+a}return n}function fe(...t){let e=0;for(let n=0;n<t.length;n++){let o=t[n];D(o),e+=o.length}let r=new Uint8Array(e);for(let n=0,o=0;n<t.length;n++){let i=t[n];r.set(i,o),o+=i.length}return r}function Ar(t,e={}){let r=(o,i)=>t(i).update(o).digest(),n=t(void 0);return r.outputLen=n.outputLen,r.blockLen=n.blockLen,r.create=o=>t(o),Object.assign(r,e),Object.freeze(r)}function _e(t=32){let e=typeof globalThis=="object"?globalThis.crypto:null;if(typeof e?.getRandomValues!="function")throw new Error("crypto.getRandomValues must be defined");return e.getRandomValues(new Uint8Array(t))}var Ir=t=>({oid:Uint8Array.from([6,9,96,134,72,1,101,3,4,2,t])});p();p();function kr(t,e,r){return t&e^~t&r}function Sr(t,e,r){return t&e^t&r^e&r}var tt=class{blockLen;outputLen;padOffset;isLE;buffer;view;finished=!1;length=0;pos=0;destroyed=!1;constructor(e,r,n,o){this.blockLen=e,this.outputLen=r,this.padOffset=n,this.isLE=o,this.buffer=new Uint8Array(e),this.view=et(this.buffer)}update(e){kt(this),D(e);let{view:r,buffer:n,blockLen:o}=this,i=e.length;for(let s=0;s<i;){let a=Math.min(o-this.pos,i-s);if(a===o){let l=et(e);for(;o<=i-s;s+=o)this.process(l,s);continue}n.set(e.subarray(s,s+a),this.pos),this.pos+=a,s+=a,this.pos===o&&(this.process(r,0),this.pos=0)}return this.length+=e.length,this.roundClean(),this}digestInto(e){kt(this),vr(e,this),this.finished=!0;let{buffer:r,view:n,blockLen:o,isLE:i}=this,{pos:s}=this;r[s++]=128,$e(this.buffer.subarray(s)),this.padOffset>o-s&&(this.process(n,0),s=0);for(let u=s;u<o;u++)r[u]=0;n.setBigUint64(o-8,BigInt(this.length*8),i),this.process(n,0);let a=et(e),l=this.outputLen;if(l%4)throw new Error("_sha2: outputLen must be aligned to 32bit");let c=l/4,f=this.get();if(c>f.length)throw new Error("_sha2: outputLen bigger than state");for(let u=0;u<c;u++)a.setUint32(4*u,f[u],i)}digest(){let{buffer:e,outputLen:r}=this;this.digestInto(e);let n=e.slice(0,r);return this.destroy(),n}_cloneInto(e){e||=new this.constructor,e.set(...this.get());let{blockLen:r,buffer:n,length:o,finished:i,destroyed:s,pos:a}=this;return e.destroyed=s,e.finished=i,e.length=o,e.pos=a,o%r&&e.buffer.set(n),e}clone(){return this._cloneInto()}},ce=Uint32Array.from([1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225]);var ho=Uint32Array.from([1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),de=new Uint32Array(64),St=class extends tt{constructor(e){super(64,e,8,!1)}get(){let{A:e,B:r,C:n,D:o,E:i,F:s,G:a,H:l}=this;return[e,r,n,o,i,s,a,l]}set(e,r,n,o,i,s,a,l){this.A=e|0,this.B=r|0,this.C=n|0,this.D=o|0,this.E=i|0,this.F=s|0,this.G=a|0,this.H=l|0}process(e,r){for(let u=0;u<16;u++,r+=4)de[u]=e.getUint32(r,!1);for(let u=16;u<64;u++){let m=de[u-15],h=de[u-2],B=Q(m,7)^Q(m,18)^m>>>3,E=Q(h,17)^Q(h,19)^h>>>10;de[u]=E+de[u-7]+B+de[u-16]|0}let{A:n,B:o,C:i,D:s,E:a,F:l,G:c,H:f}=this;for(let u=0;u<64;u++){let m=Q(a,6)^Q(a,11)^Q(a,25),h=f+m+kr(a,l,c)+ho[u]+de[u]|0,E=(Q(n,2)^Q(n,13)^Q(n,22))+Sr(n,o,i)|0;f=c,c=l,l=a,a=s+h|0,s=i,i=o,o=n,n=h+E|0}n=n+this.A|0,o=o+this.B|0,i=i+this.C|0,s=s+this.D|0,a=a+this.E|0,l=l+this.F|0,c=c+this.G|0,f=f+this.H|0,this.set(n,o,i,s,a,l,c,f)}roundClean(){$e(de)}destroy(){this.set(0,0,0,0,0,0,0,0),$e(this.buffer)}},Tt=class extends St{A=ce[0]|0;B=ce[1]|0;C=ce[2]|0;D=ce[3]|0;E=ce[4]|0;F=ce[5]|0;G=ce[6]|0;H=ce[7]|0;constructor(){super(32)}};var Ze=Ar(()=>new Tt,Ir(1));p();function rt(t){return t instanceof Uint8Array||ArrayBuffer.isView(t)&&t.constructor.name==="Uint8Array"}function Tr(t,e){return Array.isArray(e)?e.length===0?!0:t?e.every(r=>typeof r=="string"):e.every(r=>Number.isSafeInteger(r)):!1}function yo(t){if(typeof t!="function")throw new Error("function expected");return!0}function nt(t,e){if(typeof e!="string")throw new Error(`${t}: string expected`);return!0}function Ce(t){if(!Number.isSafeInteger(t))throw new Error(`invalid integer: ${t}`)}function ot(t){if(!Array.isArray(t))throw new Error("array expected")}function it(t,e){if(!Tr(!0,e))throw new Error(`${t}: array of strings expected`)}function Rr(t,e){if(!Tr(!1,e))throw new Error(`${t}: array of numbers expected`)}function mo(...t){let e=i=>i,r=(i,s)=>a=>i(s(a)),n=t.map(i=>i.encode).reduceRight(r,e),o=t.map(i=>i.decode).reduce(r,e);return{encode:n,decode:o}}function go(t){let e=typeof t=="string"?t.split(""):t,r=e.length;it("alphabet",e);let n=new Map(e.map((o,i)=>[o,i]));return{encode:o=>(ot(o),o.map(i=>{if(!Number.isSafeInteger(i)||i<0||i>=r)throw new Error(`alphabet.encode: digit index outside alphabet "${i}". Allowed: ${t}`);return e[i]})),decode:o=>(ot(o),o.map(i=>{nt("alphabet.decode",i);let s=n.get(i);if(s===void 0)throw new Error(`Unknown letter: "${i}". Allowed: ${t}`);return s}))}}function bo(t=""){return nt("join",t),{encode:e=>(it("join.decode",e),e.join(t)),decode:e=>(nt("join.decode",e),e.split(t))}}function wo(t,e="="){return Ce(t),nt("padding",e),{encode(r){for(it("padding.encode",r);r.length*t%8;)r.push(e);return r},decode(r){it("padding.decode",r);let n=r.length;if(n*t%8)throw new Error("padding: invalid, string should have whole number of bytes");for(;n>0&&r[n-1]===e;n--)if((n-1)*t%8===0)throw new Error("padding: invalid, string has too much padding");return r.slice(0,n)}}}function _t(t,e,r){if(e<2)throw new Error(`convertRadix: invalid from=${e}, base cannot be less than 2`);if(r<2)throw new Error(`convertRadix: invalid to=${r}, base cannot be less than 2`);if(ot(t),!t.length)return[];let n=0,o=[],i=Array.from(t,a=>{if(Ce(a),a<0||a>=e)throw new Error(`invalid integer: ${a}`);return a}),s=i.length;for(;;){let a=0,l=!0;for(let c=n;c<s;c++){let f=i[c],u=e*a,m=u+f;if(!Number.isSafeInteger(m)||u/e!==a||m-f!==u)throw new Error("convertRadix: carry overflow");let h=m/r;a=m%r;let B=Math.floor(h);if(i[c]=B,!Number.isSafeInteger(B)||B*r+a!==m)throw new Error("convertRadix: carry overflow");if(l)B?l=!1:n=c;else continue}if(o.push(a),l)break}for(let a=0;a<t.length-1&&t[a]===0;a++)o.push(0);return o.reverse()}var _r=(t,e)=>e===0?t:_r(e,t%e),st=(t,e)=>t+(e-_r(t,e)),Rt=(()=>{let t=[];for(let e=0;e<40;e++)t.push(2**e);return t})();function Ct(t,e,r,n){if(ot(t),e<=0||e>32)throw new Error(`convertRadix2: wrong from=${e}`);if(r<=0||r>32)throw new Error(`convertRadix2: wrong to=${r}`);if(st(e,r)>32)throw new Error(`convertRadix2: carry overflow from=${e} to=${r} carryBits=${st(e,r)}`);let o=0,i=0,s=Rt[e],a=Rt[r]-1,l=[];for(let c of t){if(Ce(c),c>=s)throw new Error(`convertRadix2: invalid data word=${c} from=${e}`);if(o=o<<e|c,i+e>32)throw new Error(`convertRadix2: carry overflow pos=${i} from=${e}`);for(i+=e;i>=r;i-=r)l.push((o>>i-r&a)>>>0);let f=Rt[i];if(f===void 0)throw new Error("invalid carry");o&=f-1}if(o=o<<r-i&a,!n&&i>=e)throw new Error("Excess padding");if(!n&&o>0)throw new Error(`Non-zero padding: ${o}`);return n&&i>0&&l.push(o>>>0),l}function xo(t){Ce(t);let e=2**8;return{encode:r=>{if(!rt(r))throw new Error("radix.encode input should be Uint8Array");return _t(Array.from(r),e,t)},decode:r=>(Rr("radix.decode",r),Uint8Array.from(_t(r,t,e)))}}function Eo(t,e=!1){if(Ce(t),t<=0||t>32)throw new Error("radix2: bits should be in (0..32]");if(st(8,t)>32||st(t,8)>32)throw new Error("radix2: carry overflow");return{encode:r=>{if(!rt(r))throw new Error("radix2.encode input should be Uint8Array");return Ct(Array.from(r),8,t,!e)},decode:r=>(Rr("radix2.decode",r),Uint8Array.from(Ct(r,t,8,e)))}}function vo(t,e){return Ce(t),yo(e),{encode(r){if(!rt(r))throw new Error("checksum.encode: input should be Uint8Array");let n=e(r).slice(0,t),o=new Uint8Array(r.length+t);return o.set(r),o.set(n,r.length),o},decode(r){if(!rt(r))throw new Error("checksum.decode: input should be Uint8Array");let n=r.slice(0,-t),o=r.slice(-t),i=e(n).slice(0,t);for(let s=0;s<t;s++)if(i[s]!==o[s])throw new Error("Invalid checksum");return n}}}var Ye={alphabet:go,chain:mo,checksum:vo,convertRadix:_t,convertRadix2:Ct,radix:xo,radix2:Eo,join:bo,padding:wo};function Bo(t){if(typeof t!="string")throw new TypeError("invalid mnemonic type: "+typeof t);return t.normalize("NFKD")}function Ao(t){let e=Bo(t),r=e.split(" ");if(![12,15,18,21,24].includes(r.length))throw new Error("Invalid mnemonic");return{nfkd:e,words:r}}function Io(t){if(D(t),![16,20,24,28,32].includes(t.length))throw new Error("invalid entropy length")}var ko=t=>{let e=8-t.length/4;return new Uint8Array([Ze(t)[0]>>e<<e])};function So(t){if(!Array.isArray(t)||t.length!==2048||typeof t[0]!="string")throw new Error("Wordlist: expected array of 2048 strings");return t.forEach(e=>{if(typeof e!="string")throw new Error("wordlist: non-string element: "+e)}),Ye.chain(Ye.checksum(1,ko),Ye.radix2(11,!0),Ye.alphabet(t))}function Cr(t,e){let{words:r}=Ao(t),n=So(e).decode(r);return Io(n),n}function Or(t,e){try{Cr(t,e)}catch{return!1}return!0}p();var Ur=`abandon
ability
able
about
above
absent
absorb
abstract
absurd
abuse
access
accident
account
accuse
achieve
acid
acoustic
acquire
across
act
action
actor
actress
actual
adapt
add
addict
address
adjust
admit
adult
advance
advice
aerobic
affair
afford
afraid
again
age
agent
agree
ahead
aim
air
airport
aisle
alarm
album
alcohol
alert
alien
all
alley
allow
almost
alone
alpha
already
also
alter
always
amateur
amazing
among
amount
amused
analyst
anchor
ancient
anger
angle
angry
animal
ankle
announce
annual
another
answer
antenna
antique
anxiety
any
apart
apology
appear
apple
approve
april
arch
arctic
area
arena
argue
arm
armed
armor
army
around
arrange
arrest
arrive
arrow
art
artefact
artist
artwork
ask
aspect
assault
asset
assist
assume
asthma
athlete
atom
attack
attend
attitude
attract
auction
audit
august
aunt
author
auto
autumn
average
avocado
avoid
awake
aware
away
awesome
awful
awkward
axis
baby
bachelor
bacon
badge
bag
balance
balcony
ball
bamboo
banana
banner
bar
barely
bargain
barrel
base
basic
basket
battle
beach
bean
beauty
because
become
beef
before
begin
behave
behind
believe
below
belt
bench
benefit
best
betray
better
between
beyond
bicycle
bid
bike
bind
biology
bird
birth
bitter
black
blade
blame
blanket
blast
bleak
bless
blind
blood
blossom
blouse
blue
blur
blush
board
boat
body
boil
bomb
bone
bonus
book
boost
border
boring
borrow
boss
bottom
bounce
box
boy
bracket
brain
brand
brass
brave
bread
breeze
brick
bridge
brief
bright
bring
brisk
broccoli
broken
bronze
broom
brother
brown
brush
bubble
buddy
budget
buffalo
build
bulb
bulk
bullet
bundle
bunker
burden
burger
burst
bus
business
busy
butter
buyer
buzz
cabbage
cabin
cable
cactus
cage
cake
call
calm
camera
camp
can
canal
cancel
candy
cannon
canoe
canvas
canyon
capable
capital
captain
car
carbon
card
cargo
carpet
carry
cart
case
cash
casino
castle
casual
cat
catalog
catch
category
cattle
caught
cause
caution
cave
ceiling
celery
cement
census
century
cereal
certain
chair
chalk
champion
change
chaos
chapter
charge
chase
chat
cheap
check
cheese
chef
cherry
chest
chicken
chief
child
chimney
choice
choose
chronic
chuckle
chunk
churn
cigar
cinnamon
circle
citizen
city
civil
claim
clap
clarify
claw
clay
clean
clerk
clever
click
client
cliff
climb
clinic
clip
clock
clog
close
cloth
cloud
clown
club
clump
cluster
clutch
coach
coast
coconut
code
coffee
coil
coin
collect
color
column
combine
come
comfort
comic
common
company
concert
conduct
confirm
congress
connect
consider
control
convince
cook
cool
copper
copy
coral
core
corn
correct
cost
cotton
couch
country
couple
course
cousin
cover
coyote
crack
cradle
craft
cram
crane
crash
crater
crawl
crazy
cream
credit
creek
crew
cricket
crime
crisp
critic
crop
cross
crouch
crowd
crucial
cruel
cruise
crumble
crunch
crush
cry
crystal
cube
culture
cup
cupboard
curious
current
curtain
curve
cushion
custom
cute
cycle
dad
damage
damp
dance
danger
daring
dash
daughter
dawn
day
deal
debate
debris
decade
december
decide
decline
decorate
decrease
deer
defense
define
defy
degree
delay
deliver
demand
demise
denial
dentist
deny
depart
depend
deposit
depth
deputy
derive
describe
desert
design
desk
despair
destroy
detail
detect
develop
device
devote
diagram
dial
diamond
diary
dice
diesel
diet
differ
digital
dignity
dilemma
dinner
dinosaur
direct
dirt
disagree
discover
disease
dish
dismiss
disorder
display
distance
divert
divide
divorce
dizzy
doctor
document
dog
doll
dolphin
domain
donate
donkey
donor
door
dose
double
dove
draft
dragon
drama
drastic
draw
dream
dress
drift
drill
drink
drip
drive
drop
drum
dry
duck
dumb
dune
during
dust
dutch
duty
dwarf
dynamic
eager
eagle
early
earn
earth
easily
east
easy
echo
ecology
economy
edge
edit
educate
effort
egg
eight
either
elbow
elder
electric
elegant
element
elephant
elevator
elite
else
embark
embody
embrace
emerge
emotion
employ
empower
empty
enable
enact
end
endless
endorse
enemy
energy
enforce
engage
engine
enhance
enjoy
enlist
enough
enrich
enroll
ensure
enter
entire
entry
envelope
episode
equal
equip
era
erase
erode
erosion
error
erupt
escape
essay
essence
estate
eternal
ethics
evidence
evil
evoke
evolve
exact
example
excess
exchange
excite
exclude
excuse
execute
exercise
exhaust
exhibit
exile
exist
exit
exotic
expand
expect
expire
explain
expose
express
extend
extra
eye
eyebrow
fabric
face
faculty
fade
faint
faith
fall
false
fame
family
famous
fan
fancy
fantasy
farm
fashion
fat
fatal
father
fatigue
fault
favorite
feature
february
federal
fee
feed
feel
female
fence
festival
fetch
fever
few
fiber
fiction
field
figure
file
film
filter
final
find
fine
finger
finish
fire
firm
first
fiscal
fish
fit
fitness
fix
flag
flame
flash
flat
flavor
flee
flight
flip
float
flock
floor
flower
fluid
flush
fly
foam
focus
fog
foil
fold
follow
food
foot
force
forest
forget
fork
fortune
forum
forward
fossil
foster
found
fox
fragile
frame
frequent
fresh
friend
fringe
frog
front
frost
frown
frozen
fruit
fuel
fun
funny
furnace
fury
future
gadget
gain
galaxy
gallery
game
gap
garage
garbage
garden
garlic
garment
gas
gasp
gate
gather
gauge
gaze
general
genius
genre
gentle
genuine
gesture
ghost
giant
gift
giggle
ginger
giraffe
girl
give
glad
glance
glare
glass
glide
glimpse
globe
gloom
glory
glove
glow
glue
goat
goddess
gold
good
goose
gorilla
gospel
gossip
govern
gown
grab
grace
grain
grant
grape
grass
gravity
great
green
grid
grief
grit
grocery
group
grow
grunt
guard
guess
guide
guilt
guitar
gun
gym
habit
hair
half
hammer
hamster
hand
happy
harbor
hard
harsh
harvest
hat
have
hawk
hazard
head
health
heart
heavy
hedgehog
height
hello
helmet
help
hen
hero
hidden
high
hill
hint
hip
hire
history
hobby
hockey
hold
hole
holiday
hollow
home
honey
hood
hope
horn
horror
horse
hospital
host
hotel
hour
hover
hub
huge
human
humble
humor
hundred
hungry
hunt
hurdle
hurry
hurt
husband
hybrid
ice
icon
idea
identify
idle
ignore
ill
illegal
illness
image
imitate
immense
immune
impact
impose
improve
impulse
inch
include
income
increase
index
indicate
indoor
industry
infant
inflict
inform
inhale
inherit
initial
inject
injury
inmate
inner
innocent
input
inquiry
insane
insect
inside
inspire
install
intact
interest
into
invest
invite
involve
iron
island
isolate
issue
item
ivory
jacket
jaguar
jar
jazz
jealous
jeans
jelly
jewel
job
join
joke
journey
joy
judge
juice
jump
jungle
junior
junk
just
kangaroo
keen
keep
ketchup
key
kick
kid
kidney
kind
kingdom
kiss
kit
kitchen
kite
kitten
kiwi
knee
knife
knock
know
lab
label
labor
ladder
lady
lake
lamp
language
laptop
large
later
latin
laugh
laundry
lava
law
lawn
lawsuit
layer
lazy
leader
leaf
learn
leave
lecture
left
leg
legal
legend
leisure
lemon
lend
length
lens
leopard
lesson
letter
level
liar
liberty
library
license
life
lift
light
like
limb
limit
link
lion
liquid
list
little
live
lizard
load
loan
lobster
local
lock
logic
lonely
long
loop
lottery
loud
lounge
love
loyal
lucky
luggage
lumber
lunar
lunch
luxury
lyrics
machine
mad
magic
magnet
maid
mail
main
major
make
mammal
man
manage
mandate
mango
mansion
manual
maple
marble
march
margin
marine
market
marriage
mask
mass
master
match
material
math
matrix
matter
maximum
maze
meadow
mean
measure
meat
mechanic
medal
media
melody
melt
member
memory
mention
menu
mercy
merge
merit
merry
mesh
message
metal
method
middle
midnight
milk
million
mimic
mind
minimum
minor
minute
miracle
mirror
misery
miss
mistake
mix
mixed
mixture
mobile
model
modify
mom
moment
monitor
monkey
monster
month
moon
moral
more
morning
mosquito
mother
motion
motor
mountain
mouse
move
movie
much
muffin
mule
multiply
muscle
museum
mushroom
music
must
mutual
myself
mystery
myth
naive
name
napkin
narrow
nasty
nation
nature
near
neck
need
negative
neglect
neither
nephew
nerve
nest
net
network
neutral
never
news
next
nice
night
noble
noise
nominee
noodle
normal
north
nose
notable
note
nothing
notice
novel
now
nuclear
number
nurse
nut
oak
obey
object
oblige
obscure
observe
obtain
obvious
occur
ocean
october
odor
off
offer
office
often
oil
okay
old
olive
olympic
omit
once
one
onion
online
only
open
opera
opinion
oppose
option
orange
orbit
orchard
order
ordinary
organ
orient
original
orphan
ostrich
other
outdoor
outer
output
outside
oval
oven
over
own
owner
oxygen
oyster
ozone
pact
paddle
page
pair
palace
palm
panda
panel
panic
panther
paper
parade
parent
park
parrot
party
pass
patch
path
patient
patrol
pattern
pause
pave
payment
peace
peanut
pear
peasant
pelican
pen
penalty
pencil
people
pepper
perfect
permit
person
pet
phone
photo
phrase
physical
piano
picnic
picture
piece
pig
pigeon
pill
pilot
pink
pioneer
pipe
pistol
pitch
pizza
place
planet
plastic
plate
play
please
pledge
pluck
plug
plunge
poem
poet
point
polar
pole
police
pond
pony
pool
popular
portion
position
possible
post
potato
pottery
poverty
powder
power
practice
praise
predict
prefer
prepare
present
pretty
prevent
price
pride
primary
print
priority
prison
private
prize
problem
process
produce
profit
program
project
promote
proof
property
prosper
protect
proud
provide
public
pudding
pull
pulp
pulse
pumpkin
punch
pupil
puppy
purchase
purity
purpose
purse
push
put
puzzle
pyramid
quality
quantum
quarter
question
quick
quit
quiz
quote
rabbit
raccoon
race
rack
radar
radio
rail
rain
raise
rally
ramp
ranch
random
range
rapid
rare
rate
rather
raven
raw
razor
ready
real
reason
rebel
rebuild
recall
receive
recipe
record
recycle
reduce
reflect
reform
refuse
region
regret
regular
reject
relax
release
relief
rely
remain
remember
remind
remove
render
renew
rent
reopen
repair
repeat
replace
report
require
rescue
resemble
resist
resource
response
result
retire
retreat
return
reunion
reveal
review
reward
rhythm
rib
ribbon
rice
rich
ride
ridge
rifle
right
rigid
ring
riot
ripple
risk
ritual
rival
river
road
roast
robot
robust
rocket
romance
roof
rookie
room
rose
rotate
rough
round
route
royal
rubber
rude
rug
rule
run
runway
rural
sad
saddle
sadness
safe
sail
salad
salmon
salon
salt
salute
same
sample
sand
satisfy
satoshi
sauce
sausage
save
say
scale
scan
scare
scatter
scene
scheme
school
science
scissors
scorpion
scout
scrap
screen
script
scrub
sea
search
season
seat
second
secret
section
security
seed
seek
segment
select
sell
seminar
senior
sense
sentence
series
service
session
settle
setup
seven
shadow
shaft
shallow
share
shed
shell
sheriff
shield
shift
shine
ship
shiver
shock
shoe
shoot
shop
short
shoulder
shove
shrimp
shrug
shuffle
shy
sibling
sick
side
siege
sight
sign
silent
silk
silly
silver
similar
simple
since
sing
siren
sister
situate
six
size
skate
sketch
ski
skill
skin
skirt
skull
slab
slam
sleep
slender
slice
slide
slight
slim
slogan
slot
slow
slush
small
smart
smile
smoke
smooth
snack
snake
snap
sniff
snow
soap
soccer
social
sock
soda
soft
solar
soldier
solid
solution
solve
someone
song
soon
sorry
sort
soul
sound
soup
source
south
space
spare
spatial
spawn
speak
special
speed
spell
spend
sphere
spice
spider
spike
spin
spirit
split
spoil
sponsor
spoon
sport
spot
spray
spread
spring
spy
square
squeeze
squirrel
stable
stadium
staff
stage
stairs
stamp
stand
start
state
stay
steak
steel
stem
step
stereo
stick
still
sting
stock
stomach
stone
stool
story
stove
strategy
street
strike
strong
struggle
student
stuff
stumble
style
subject
submit
subway
success
such
sudden
suffer
sugar
suggest
suit
summer
sun
sunny
sunset
super
supply
supreme
sure
surface
surge
surprise
surround
survey
suspect
sustain
swallow
swamp
swap
swarm
swear
sweet
swift
swim
swing
switch
sword
symbol
symptom
syrup
system
table
tackle
tag
tail
talent
talk
tank
tape
target
task
taste
tattoo
taxi
teach
team
tell
ten
tenant
tennis
tent
term
test
text
thank
that
theme
then
theory
there
they
thing
this
thought
three
thrive
throw
thumb
thunder
ticket
tide
tiger
tilt
timber
time
tiny
tip
tired
tissue
title
toast
tobacco
today
toddler
toe
together
toilet
token
tomato
tomorrow
tone
tongue
tonight
tool
tooth
top
topic
topple
torch
tornado
tortoise
toss
total
tourist
toward
tower
town
toy
track
trade
traffic
tragic
train
transfer
trap
trash
travel
tray
treat
tree
trend
trial
tribe
trick
trigger
trim
trip
trophy
trouble
truck
true
truly
trumpet
trust
truth
try
tube
tuition
tumble
tuna
tunnel
turkey
turn
turtle
twelve
twenty
twice
twin
twist
two
type
typical
ugly
umbrella
unable
unaware
uncle
uncover
under
undo
unfair
unfold
unhappy
uniform
unique
unit
universe
unknown
unlock
until
unusual
unveil
update
upgrade
uphold
upon
upper
upset
urban
urge
usage
use
used
useful
useless
usual
utility
vacant
vacuum
vague
valid
valley
valve
van
vanish
vapor
various
vast
vault
vehicle
velvet
vendor
venture
venue
verb
verify
version
very
vessel
veteran
viable
vibrant
vicious
victory
video
view
village
vintage
violin
virtual
virus
visa
visit
visual
vital
vivid
vocal
voice
void
volcano
volume
vote
voyage
wage
wagon
wait
walk
wall
walnut
want
warfare
warm
warrior
wash
wasp
waste
water
wave
way
wealth
weapon
wear
weasel
weather
web
wedding
weekend
weird
welcome
west
wet
whale
what
wheat
wheel
when
where
whip
whisper
wide
width
wife
wild
will
win
window
wine
wing
wink
winner
winter
wire
wisdom
wise
wish
witness
wolf
woman
wonder
wood
wool
word
work
world
worry
worth
wrap
wreck
wrestle
wrist
write
wrong
yard
year
yellow
you
young
youth
zebra
zero
zone
zoo`.split(`
`);p();p();p();var Lr;(function(t){t[t.SET_METADATA=0]="SET_METADATA",t[t.TEXT_NOTE=1]="TEXT_NOTE",t[t.RECOMMEND_SERVER=2]="RECOMMEND_SERVER",t[t.CONTACTS=3]="CONTACTS",t[t.ENCRYPTED_DIRECT_MESSAGE=4]="ENCRYPTED_DIRECT_MESSAGE",t[t.EVENT_DELETION=5]="EVENT_DELETION",t[t.REPOST=6]="REPOST",t[t.REACTION=7]="REACTION",t[t.CHANNEL_CREATION=40]="CHANNEL_CREATION",t[t.CHANNEL_METADATA=41]="CHANNEL_METADATA",t[t.CHANNEL_MESSAGE=42]="CHANNEL_MESSAGE",t[t.CHANNEL_HIDE_MESSAGE=43]="CHANNEL_HIDE_MESSAGE",t[t.CHANNEL_MUTE_USER=44]="CHANNEL_MUTE_USER",t[t.AUTH=22242]="AUTH",t[t.AUTH_RESPONSE=22243]="AUTH_RESPONSE"})(Lr||(Lr={}));var at;(function(t){t.EVENT="EVENT",t.NOTICE="NOTICE",t.OK="OK",t.EOSE="EOSE",t.REQ="REQ",t.CLOSE="CLOSE",t.AUTH="AUTH"})(at||(at={}));p();p();p();p();var ct;(function(t){t.CONNECT="connect",t.PING="ping",t.GET_PUBLIC_KEY="get_public_key",t.SIGN_EVENT="sign_event",t.NIP04_ENCRYPT="nip04_encrypt",t.NIP04_DECRYPT="nip04_decrypt",t.NIP44_ENCRYPT="nip44_encrypt",t.NIP44_DECRYPT="nip44_decrypt",t.GET_RELAYS="get_relays"})(ct||(ct={}));var Ot;(function(t){t[t.SET_METADATA=0]="SET_METADATA",t[t.TEXT_NOTE=1]="TEXT_NOTE",t[t.RECOMMEND_SERVER=2]="RECOMMEND_SERVER",t[t.CONTACT_LIST=3]="CONTACT_LIST",t[t.ENCRYPTED_DIRECT_MESSAGE=4]="ENCRYPTED_DIRECT_MESSAGE",t[t.DELETE=5]="DELETE",t[t.REPOST=6]="REPOST",t[t.REACTION=7]="REACTION",t[t.BADGE_AWARD=8]="BADGE_AWARD",t[t.CHANNEL_CREATE=40]="CHANNEL_CREATE",t[t.CHANNEL_METADATA=41]="CHANNEL_METADATA",t[t.CHANNEL_MESSAGE=42]="CHANNEL_MESSAGE",t[t.CHANNEL_HIDE_MESSAGE=43]="CHANNEL_HIDE_MESSAGE",t[t.CHANNEL_MUTE_USER=44]="CHANNEL_MUTE_USER",t[t.CHANNEL_RESERVE=45]="CHANNEL_RESERVE",t[t.REPORTING=1984]="REPORTING",t[t.ZAP_REQUEST=9734]="ZAP_REQUEST",t[t.ZAP=9735]="ZAP",t[t.MUTE_LIST=1e4]="MUTE_LIST",t[t.PIN_LIST=10001]="PIN_LIST",t[t.RELAY_LIST_METADATA=10002]="RELAY_LIST_METADATA",t[t.CLIENT_AUTH=22242]="CLIENT_AUTH",t[t.AUTH_RESPONSE=22243]="AUTH_RESPONSE",t[t.NOSTR_CONNECT=24133]="NOSTR_CONNECT",t[t.CATEGORIZED_PEOPLE=3e4]="CATEGORIZED_PEOPLE",t[t.CATEGORIZED_BOOKMARKS=30001]="CATEGORIZED_BOOKMARKS",t[t.PROFILE_BADGES=30008]="PROFILE_BADGES",t[t.BADGE_DEFINITION=30009]="BADGE_DEFINITION",t[t.LONG_FORM=30023]="LONG_FORM",t[t.APPLICATION_SPECIFIC=30078]="APPLICATION_SPECIFIC"})(Ot||(Ot={}));p();p();p();p();var Lt=BigInt(0),Ut=BigInt(1);function Nt(t,e=""){if(typeof t!="boolean"){let r=e&&`"${e}" `;throw new Error(r+"expected boolean, got type="+typeof t)}return t}function To(t){if(typeof t=="bigint"){if(!_o(t))throw new Error("positive bigint expected, got "+t)}else xe(t);return t}function Nr(t){if(typeof t!="string")throw new Error("hex string expected, got "+typeof t);return t===""?Lt:BigInt("0x"+t)}function Oe(t){return Nr(Re(t))}function Dt(t){return Nr(Re(Ro(D(t)).reverse()))}function lt(t,e){xe(e),t=To(t);let r=Ge(t.toString(16).padStart(e*2,"0"));if(r.length!==e)throw new Error("number too large");return r}function Pt(t,e){return lt(t,e).reverse()}function Ro(t){return Uint8Array.from(t)}function Dr(t){return Uint8Array.from(t,(e,r)=>{let n=e.charCodeAt(0);if(e.length!==1||n>127)throw new Error(`string contains non-ASCII character "${t[r]}" with code ${n} at position ${r}`);return n})}var _o=t=>typeof t=="bigint"&&Lt<=t;function Vt(t){let e;for(e=0;t>Lt;t>>=Ut,e+=1);return e}var ut=t=>(Ut<<BigInt(t))-Ut;function ft(t,e={},r={}){if(!t||typeof t!="object")throw new Error("expected valid options object");function n(i,s,a){let l=t[i];if(a&&l===void 0)return;let c=typeof l;if(c!==s||l===null)throw new Error(`param "${i}" is invalid: expected ${s}, got ${c}`)}let o=(i,s)=>Object.entries(i).forEach(([a,l])=>n(a,l,s));o(e,!1),o(r,!0)}function Ht(t){let e=new WeakMap;return(r,...n)=>{let o=e.get(r);if(o!==void 0)return o;let i=t(r,...n);return e.set(r,i),i}}p();var z=BigInt(0),j=BigInt(1),Ee=BigInt(2),Hr=BigInt(3),Mr=BigInt(4),Fr=BigInt(5),Co=BigInt(7),jr=BigInt(8),Oo=BigInt(9),qr=BigInt(16);function ee(t,e){let r=t%e;return r>=z?r:e+r}function Y(t,e,r){let n=t;for(;e-- >z;)n*=n,n%=r;return n}function Pr(t,e){if(t===z)throw new Error("invert: expected non-zero number");if(e<=z)throw new Error("invert: expected positive modulus, got "+e);let r=ee(t,e),n=e,o=z,i=j,s=j,a=z;for(;r!==z;){let c=n/r,f=n%r,u=o-s*c,m=i-a*c;n=r,r=f,o=s,i=a,s=u,a=m}if(n!==j)throw new Error("invert: does not exist");return ee(o,e)}function Ft(t,e,r){if(!t.eql(t.sqr(e),r))throw new Error("Cannot find square root")}function zr(t,e){let r=(t.ORDER+j)/Mr,n=t.pow(e,r);return Ft(t,n,e),n}function Uo(t,e){let r=(t.ORDER-Fr)/jr,n=t.mul(e,Ee),o=t.pow(n,r),i=t.mul(e,o),s=t.mul(t.mul(i,Ee),o),a=t.mul(i,t.sub(s,t.ONE));return Ft(t,a,e),a}function Lo(t){let e=Ue(t),r=$r(t),n=r(e,e.neg(e.ONE)),o=r(e,n),i=r(e,e.neg(n)),s=(t+Co)/qr;return(a,l)=>{let c=a.pow(l,s),f=a.mul(c,n),u=a.mul(c,o),m=a.mul(c,i),h=a.eql(a.sqr(f),l),B=a.eql(a.sqr(u),l);c=a.cmov(c,f,h),f=a.cmov(m,u,B);let E=a.eql(a.sqr(f),l),L=a.cmov(c,f,E);return Ft(a,L,l),L}}function $r(t){if(t<Hr)throw new Error("sqrt is not defined for small field");let e=t-j,r=0;for(;e%Ee===z;)e/=Ee,r++;let n=Ee,o=Ue(t);for(;Vr(o,n)===1;)if(n++>1e3)throw new Error("Cannot find square root: probably non-prime P");if(r===1)return zr;let i=o.pow(n,e),s=(e+j)/Ee;return function(l,c){if(l.is0(c))return c;if(Vr(l,c)!==1)throw new Error("Cannot find square root");let f=r,u=l.mul(l.ONE,i),m=l.pow(c,e),h=l.pow(c,s);for(;!l.eql(m,l.ONE);){if(l.is0(m))return l.ZERO;let B=1,E=l.sqr(m);for(;!l.eql(E,l.ONE);)if(B++,E=l.sqr(E),B===f)throw new Error("Cannot find square root");let L=j<<BigInt(f-B-1),F=l.pow(u,L);f=B,u=l.sqr(F),m=l.mul(m,u),h=l.mul(h,F)}return h}}function No(t){return t%Mr===Hr?zr:t%jr===Fr?Uo:t%qr===Oo?Lo(t):$r(t)}var Do=["create","isValid","is0","neg","inv","sqrt","sqr","eql","add","sub","mul","pow","div","addN","subN","mulN","sqrN"];function Gr(t){let e={ORDER:"bigint",BYTES:"number",BITS:"number"},r=Do.reduce((n,o)=>(n[o]="function",n),e);return ft(t,r),t}function Po(t,e,r){if(r<z)throw new Error("invalid exponent, negatives unsupported");if(r===z)return t.ONE;if(r===j)return e;let n=t.ONE,o=e;for(;r>z;)r&j&&(n=t.mul(n,o)),o=t.sqr(o),r>>=j;return n}function jt(t,e,r=!1){let n=new Array(e.length).fill(r?t.ZERO:void 0),o=e.reduce((s,a,l)=>t.is0(a)?s:(n[l]=s,t.mul(s,a)),t.ONE),i=t.inv(o);return e.reduceRight((s,a,l)=>t.is0(a)?s:(n[l]=t.mul(s,n[l]),t.mul(s,a)),i),n}function Vr(t,e){let r=(t.ORDER-j)/Ee,n=t.pow(e,r),o=t.eql(n,t.ONE),i=t.eql(n,t.ZERO),s=t.eql(n,t.neg(t.ONE));if(!o&&!i&&!s)throw new Error("invalid Legendre symbol result");return o?1:i?0:-1}function Vo(t,e){e!==void 0&&xe(e);let r=e!==void 0?e:t.toString(2).length,n=Math.ceil(r/8);return{nBitLength:r,nByteLength:n}}var Mt=class{ORDER;BITS;BYTES;isLE;ZERO=z;ONE=j;_lengths;_sqrt;_mod;constructor(e,r={}){if(e<=z)throw new Error("invalid field: expected ORDER > 0, got "+e);let n;this.isLE=!1,r!=null&&typeof r=="object"&&(typeof r.BITS=="number"&&(n=r.BITS),typeof r.sqrt=="function"&&(this.sqrt=r.sqrt),typeof r.isLE=="boolean"&&(this.isLE=r.isLE),r.allowedLengths&&(this._lengths=r.allowedLengths?.slice()),typeof r.modFromBytes=="boolean"&&(this._mod=r.modFromBytes));let{nBitLength:o,nByteLength:i}=Vo(e,n);if(i>2048)throw new Error("invalid field: expected ORDER of <= 2048 bytes");this.ORDER=e,this.BITS=o,this.BYTES=i,this._sqrt=void 0,Object.preventExtensions(this)}create(e){return ee(e,this.ORDER)}isValid(e){if(typeof e!="bigint")throw new Error("invalid field element: expected bigint, got "+typeof e);return z<=e&&e<this.ORDER}is0(e){return e===z}isValidNot0(e){return!this.is0(e)&&this.isValid(e)}isOdd(e){return(e&j)===j}neg(e){return ee(-e,this.ORDER)}eql(e,r){return e===r}sqr(e){return ee(e*e,this.ORDER)}add(e,r){return ee(e+r,this.ORDER)}sub(e,r){return ee(e-r,this.ORDER)}mul(e,r){return ee(e*r,this.ORDER)}pow(e,r){return Po(this,e,r)}div(e,r){return ee(e*Pr(r,this.ORDER),this.ORDER)}sqrN(e){return e*e}addN(e,r){return e+r}subN(e,r){return e-r}mulN(e,r){return e*r}inv(e){return Pr(e,this.ORDER)}sqrt(e){return this._sqrt||(this._sqrt=No(this.ORDER)),this._sqrt(this,e)}toBytes(e){return this.isLE?Pt(e,this.BYTES):lt(e,this.BYTES)}fromBytes(e,r=!1){D(e);let{_lengths:n,BYTES:o,isLE:i,ORDER:s,_mod:a}=this;if(n){if(!n.includes(e.length)||e.length>o)throw new Error("Field.fromBytes: expected "+n+" bytes, got "+e.length);let c=new Uint8Array(o);c.set(e,i?0:c.length-e.length),e=c}if(e.length!==o)throw new Error("Field.fromBytes: expected "+o+" bytes, got "+e.length);let l=i?Dt(e):Oe(e);if(a&&(l=ee(l,s)),!r&&!this.isValid(l))throw new Error("invalid field element: outside of range 0..ORDER");return l}invertBatch(e){return jt(this,e)}cmov(e,r,n){return n?r:e}};function Ue(t,e={}){return new Mt(t,e)}function Zr(t){if(typeof t!="bigint")throw new Error("field order must be bigint");let e=t.toString(2).length;return Math.ceil(e/8)}function Ho(t){let e=Zr(t);return e+Math.ceil(e/2)}function Yr(t,e,r=!1){D(t);let n=t.length,o=Zr(e),i=Ho(e);if(n<16||n<i||n>1024)throw new Error("expected "+i+"-1024 bytes of input, got "+n);let s=r?Dt(t):Oe(t),a=ee(s,e-j)+j;return r?Pt(a,o):lt(a,o)}var Le=BigInt(0),ve=BigInt(1);function We(t,e){let r=e.negate();return t?r:e}function Gt(t,e){let r=jt(t.Fp,e.map(n=>n.Z));return e.map((n,o)=>t.fromAffine(n.toAffine(r[o])))}function Jr(t,e){if(!Number.isSafeInteger(t)||t<=0||t>e)throw new Error("invalid window size, expected [1.."+e+"], got W="+t)}function qt(t,e){Jr(t,e);let r=Math.ceil(e/t)+1,n=2**(t-1),o=2**t,i=ut(t),s=BigInt(t);return{windows:r,windowSize:n,mask:i,maxNumber:o,shiftBy:s}}function Wr(t,e,r){let{windowSize:n,mask:o,maxNumber:i,shiftBy:s}=r,a=Number(t&o),l=t>>s;a>n&&(a-=i,l+=ve);let c=e*n,f=c+Math.abs(a)-1,u=a===0,m=a<0,h=e%2!==0;return{nextN:l,offset:f,isZero:u,isNeg:m,isNegF:h,offsetF:c}}var zt=new WeakMap,Qr=new WeakMap;function $t(t){return Qr.get(t)||1}function Kr(t){if(t!==Le)throw new Error("invalid wNAF")}var dt=class{BASE;ZERO;Fn;bits;constructor(e,r){this.BASE=e.BASE,this.ZERO=e.ZERO,this.Fn=e.Fn,this.bits=r}_unsafeLadder(e,r,n=this.ZERO){let o=e;for(;r>Le;)r&ve&&(n=n.add(o)),o=o.double(),r>>=ve;return n}precomputeWindow(e,r){let{windows:n,windowSize:o}=qt(r,this.bits),i=[],s=e,a=s;for(let l=0;l<n;l++){a=s,i.push(a);for(let c=1;c<o;c++)a=a.add(s),i.push(a);s=a.double()}return i}wNAF(e,r,n){if(!this.Fn.isValid(n))throw new Error("invalid scalar");let o=this.ZERO,i=this.BASE,s=qt(e,this.bits);for(let a=0;a<s.windows;a++){let{nextN:l,offset:c,isZero:f,isNeg:u,isNegF:m,offsetF:h}=Wr(n,a,s);n=l,f?i=i.add(We(m,r[h])):o=o.add(We(u,r[c]))}return Kr(n),{p:o,f:i}}wNAFUnsafe(e,r,n,o=this.ZERO){let i=qt(e,this.bits);for(let s=0;s<i.windows&&n!==Le;s++){let{nextN:a,offset:l,isZero:c,isNeg:f}=Wr(n,s,i);if(n=a,!c){let u=r[l];o=o.add(f?u.negate():u)}}return Kr(n),o}getPrecomputes(e,r,n){let o=zt.get(r);return o||(o=this.precomputeWindow(r,e),e!==1&&(typeof n=="function"&&(o=n(o)),zt.set(r,o))),o}cached(e,r,n){let o=$t(e);return this.wNAF(o,this.getPrecomputes(o,e,n),r)}unsafe(e,r,n,o){let i=$t(e);return i===1?this._unsafeLadder(e,r,o):this.wNAFUnsafe(i,this.getPrecomputes(i,e,n),r,o)}createCache(e,r){Jr(r,this.bits),Qr.set(e,r),zt.delete(e)}hasCache(e){return $t(e)!==1}};function en(t,e,r,n){let o=e,i=t.ZERO,s=t.ZERO;for(;r>Le||n>Le;)r&ve&&(i=i.add(o)),n&ve&&(s=s.add(o)),o=o.double(),r>>=ve,n>>=ve;return{p1:i,p2:s}}function Xr(t,e,r){if(e){if(e.ORDER!==t)throw new Error("Field.ORDER must match order: Fp == p, Fn == n");return Gr(e),e}else return Ue(t,{isLE:r})}function tn(t,e,r={},n){if(n===void 0&&(n=t==="edwards"),!e||typeof e!="object")throw new Error(`expected valid ${t} CURVE object`);for(let l of["p","n","h"]){let c=e[l];if(!(typeof c=="bigint"&&c>Le))throw new Error(`CURVE.${l} must be positive bigint`)}let o=Xr(e.p,r.Fp,n),i=Xr(e.n,r.Fn,n),a=["Gx","Gy","a",t==="weierstrass"?"b":"d"];for(let l of a)if(!o.isValid(e[l]))throw new Error(`CURVE.${l} must be valid field element of CURVE.Fp`);return e=Object.freeze(Object.assign({},e)),{CURVE:e,Fp:o,Fn:i}}function Zt(t,e){return function(n){let o=t(n);return{secretKey:o,publicKey:e(o)}}}p();var rn=(t,e)=>(t+(t>=0?e:-e)/Fo)/e;function Mo(t,e,r){let[[n,o],[i,s]]=e,a=rn(s*t,r),l=rn(-o*t,r),c=t-a*n-l*i,f=-a*o-l*s,u=c<Ke,m=f<Ke;u&&(c=-c),m&&(f=-f);let h=ut(Math.ceil(Vt(r)/2))+ht;if(c<Ke||c>=h||f<Ke||f>=h)throw new Error("splitScalar (endomorphism): failed, k="+t);return{k1neg:u,k1:c,k2neg:m,k2:f}}var Ke=BigInt(0),ht=BigInt(1),Fo=BigInt(2),pt=BigInt(3),jo=BigInt(4);function nn(t,e={}){let r=tn("weierstrass",t,e),{Fp:n,Fn:o}=r,i=r.CURVE,{h:s,n:a}=i;ft(e,{},{allowInfinityPoint:"boolean",clearCofactor:"function",isTorsionFree:"function",fromBytes:"function",toBytes:"function",endo:"object"});let{endo:l}=e;if(l&&(!n.is0(i.a)||typeof l.beta!="bigint"||!Array.isArray(l.basises)))throw new Error('invalid endo: expected "beta": bigint and "basises": array');let c=zo(n,o);function f(){if(!n.isOdd)throw new Error("compression is not supported: Field does not have .isOdd()")}function u(_,y,w){let{x:A,y:I}=y.toAffine(),O=n.toBytes(A);if(Nt(w,"isCompressed"),w){f();let T=!n.isOdd(I);return fe(qo(T),O)}else return fe(Uint8Array.of(4),O,n.toBytes(I))}function m(_){D(_,void 0,"Point");let{publicKey:y,publicKeyUncompressed:w}=c,A=_.length,I=_[0],O=_.subarray(1);if(A===y&&(I===2||I===3)){let T=n.fromBytes(O);if(!n.isValid(T))throw new Error("bad point: is not on curve, wrong x");let k=E(T),v;try{v=n.sqrt(k)}catch(W){let H=W instanceof Error?": "+W.message:"";throw new Error("bad point: is not on curve, sqrt error"+H)}f();let S=n.isOdd(v);return(I&1)===1!==S&&(v=n.neg(v)),{x:T,y:v}}else if(A===w&&I===4){let T=n.BYTES,k=n.fromBytes(O.subarray(0,T)),v=n.fromBytes(O.subarray(T,T*2));if(!L(k,v))throw new Error("bad point: is not on curve");return{x:k,y:v}}else throw new Error(`bad point: got length ${A}, expected compressed=${y} or uncompressed=${w}`)}let h=e.toBytes||u,B=e.fromBytes||m;function E(_){let y=n.sqr(_),w=n.mul(y,_);return n.add(n.add(w,n.mul(_,i.a)),i.b)}function L(_,y){let w=n.sqr(y),A=E(_);return n.eql(w,A)}if(!L(i.Gx,i.Gy))throw new Error("bad curve params: generator point");let F=n.mul(n.pow(i.a,pt),jo),ke=n.mul(n.sqr(i.b),BigInt(27));if(n.is0(n.add(F,ke)))throw new Error("bad curve params: a or b");function re(_,y,w=!1){if(!n.isValid(y)||w&&n.is0(y))throw new Error(`bad point coordinate ${_}`);return y}function ge(_){if(!(_ instanceof N))throw new Error("Weierstrass Point expected")}function be(_){if(!l||!l.basises)throw new Error("no endo");return Mo(_,l.basises,o.ORDER)}let ne=Ht((_,y)=>{let{X:w,Y:A,Z:I}=_;if(n.eql(I,n.ONE))return{x:w,y:A};let O=_.is0();y==null&&(y=O?n.ONE:n.inv(I));let T=n.mul(w,y),k=n.mul(A,y),v=n.mul(I,y);if(O)return{x:n.ZERO,y:n.ZERO};if(!n.eql(v,n.ONE))throw new Error("invZ was invalid");return{x:T,y:k}}),Se=Ht(_=>{if(_.is0()){if(e.allowInfinityPoint&&!n.is0(_.Y))return;throw new Error("bad point: ZERO")}let{x:y,y:w}=_.toAffine();if(!n.isValid(y)||!n.isValid(w))throw new Error("bad point: x or y not field elements");if(!L(y,w))throw new Error("bad point: equation left != right");if(!_.isTorsionFree())throw new Error("bad point: not in prime-order subgroup");return!0});function br(_,y,w,A,I){return w=new N(n.mul(w.X,_),w.Y,w.Z),y=We(A,y),w=We(I,w),y.add(w)}class N{static BASE=new N(i.Gx,i.Gy,n.ONE);static ZERO=new N(n.ZERO,n.ONE,n.ZERO);static Fp=n;static Fn=o;X;Y;Z;constructor(y,w,A){this.X=re("x",y),this.Y=re("y",w,!0),this.Z=re("z",A),Object.freeze(this)}static CURVE(){return i}static fromAffine(y){let{x:w,y:A}=y||{};if(!y||!n.isValid(w)||!n.isValid(A))throw new Error("invalid affine point");if(y instanceof N)throw new Error("projective point not allowed");return n.is0(w)&&n.is0(A)?N.ZERO:new N(w,A,n.ONE)}static fromBytes(y){let w=N.fromAffine(B(D(y,void 0,"point")));return w.assertValidity(),w}static fromHex(y){return N.fromBytes(Ge(y))}get x(){return this.toAffine().x}get y(){return this.toAffine().y}precompute(y=8,w=!0){return qe.createCache(this,y),w||this.multiply(pt),this}assertValidity(){Se(this)}hasEvenY(){let{y}=this.toAffine();if(!n.isOdd)throw new Error("Field doesn't support isOdd");return!n.isOdd(y)}equals(y){ge(y);let{X:w,Y:A,Z:I}=this,{X:O,Y:T,Z:k}=y,v=n.eql(n.mul(w,k),n.mul(O,I)),S=n.eql(n.mul(A,k),n.mul(T,I));return v&&S}negate(){return new N(this.X,n.neg(this.Y),this.Z)}double(){let{a:y,b:w}=i,A=n.mul(w,pt),{X:I,Y:O,Z:T}=this,k=n.ZERO,v=n.ZERO,S=n.ZERO,R=n.mul(I,I),W=n.mul(O,O),H=n.mul(T,T),U=n.mul(I,O);return U=n.add(U,U),S=n.mul(I,T),S=n.add(S,S),k=n.mul(y,S),v=n.mul(A,H),v=n.add(k,v),k=n.sub(W,v),v=n.add(W,v),v=n.mul(k,v),k=n.mul(U,k),S=n.mul(A,S),H=n.mul(y,H),U=n.sub(R,H),U=n.mul(y,U),U=n.add(U,S),S=n.add(R,R),R=n.add(S,R),R=n.add(R,H),R=n.mul(R,U),v=n.add(v,R),H=n.mul(O,T),H=n.add(H,H),R=n.mul(H,U),k=n.sub(k,R),S=n.mul(H,W),S=n.add(S,S),S=n.add(S,S),new N(k,v,S)}add(y){ge(y);let{X:w,Y:A,Z:I}=this,{X:O,Y:T,Z:k}=y,v=n.ZERO,S=n.ZERO,R=n.ZERO,W=i.a,H=n.mul(i.b,pt),U=n.mul(w,O),X=n.mul(A,T),J=n.mul(I,k),Te=n.add(w,A),q=n.add(O,T);Te=n.mul(Te,q),q=n.add(U,X),Te=n.sub(Te,q),q=n.add(w,I);let oe=n.add(O,k);return q=n.mul(q,oe),oe=n.add(U,J),q=n.sub(q,oe),oe=n.add(A,I),v=n.add(T,k),oe=n.mul(oe,v),v=n.add(X,J),oe=n.sub(oe,v),R=n.mul(W,q),v=n.mul(H,J),R=n.add(v,R),v=n.sub(X,R),R=n.add(X,R),S=n.mul(v,R),X=n.add(U,U),X=n.add(X,U),J=n.mul(W,J),q=n.mul(H,q),X=n.add(X,J),J=n.sub(U,J),J=n.mul(W,J),q=n.add(q,J),U=n.mul(X,q),S=n.add(S,U),U=n.mul(oe,q),v=n.mul(Te,v),v=n.sub(v,U),U=n.mul(Te,X),R=n.mul(oe,R),R=n.add(R,U),new N(v,S,R)}subtract(y){return this.add(y.negate())}is0(){return this.equals(N.ZERO)}multiply(y){let{endo:w}=e;if(!o.isValidNot0(y))throw new Error("invalid scalar: out of range");let A,I,O=T=>qe.cached(this,T,k=>Gt(N,k));if(w){let{k1neg:T,k1:k,k2neg:v,k2:S}=be(y),{p:R,f:W}=O(k),{p:H,f:U}=O(S);I=W.add(U),A=br(w.beta,R,H,T,v)}else{let{p:T,f:k}=O(y);A=T,I=k}return Gt(N,[A,I])[0]}multiplyUnsafe(y){let{endo:w}=e,A=this;if(!o.isValid(y))throw new Error("invalid scalar: out of range");if(y===Ke||A.is0())return N.ZERO;if(y===ht)return A;if(qe.hasCache(this))return this.multiply(y);if(w){let{k1neg:I,k1:O,k2neg:T,k2:k}=be(y),{p1:v,p2:S}=en(N,A,O,k);return br(w.beta,v,S,I,T)}else return qe.unsafe(A,y)}toAffine(y){return ne(this,y)}isTorsionFree(){let{isTorsionFree:y}=e;return s===ht?!0:y?y(N,this):qe.unsafe(this,a).is0()}clearCofactor(){let{clearCofactor:y}=e;return s===ht?this:y?y(N,this):this.multiplyUnsafe(s)}isSmallOrder(){return this.multiplyUnsafe(s).is0()}toBytes(y=!0){return Nt(y,"isCompressed"),this.assertValidity(),h(N,this,y)}toHex(y=!0){return Re(this.toBytes(y))}toString(){return`<Point ${this.is0()?"ZERO":this.toHex()}>`}}let wr=o.BITS,qe=new dt(N,e.endo?Math.ceil(wr/2):wr);return N.BASE.precompute(8),N}function qo(t){return Uint8Array.of(t?2:3)}function zo(t,e){return{secretKey:e.BYTES,publicKey:1+t.BYTES,publicKeyUncompressed:1+2*t.BYTES,publicKeyHasPrefix:!0,signature:2*e.BYTES}}var gt={p:BigInt("0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f"),n:BigInt("0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141"),h:BigInt(1),a:BigInt(0),b:BigInt(7),Gx:BigInt("0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"),Gy:BigInt("0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8")},$o={beta:BigInt("0x7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501ee"),basises:[[BigInt("0x3086d221a7d46bcde86c90e49284eb15"),-BigInt("0xe4437ed6010e88286f547fa90abfe4c3")],[BigInt("0x114ca50f7a8e2f3f657c1108d9d44cfd8"),BigInt("0x3086d221a7d46bcde86c90e49284eb15")]]},Go=BigInt(0),Yt=BigInt(2);function Zo(t){let e=gt.p,r=BigInt(3),n=BigInt(6),o=BigInt(11),i=BigInt(22),s=BigInt(23),a=BigInt(44),l=BigInt(88),c=t*t*t%e,f=c*c*t%e,u=Y(f,r,e)*f%e,m=Y(u,r,e)*f%e,h=Y(m,Yt,e)*c%e,B=Y(h,o,e)*h%e,E=Y(B,i,e)*B%e,L=Y(E,a,e)*E%e,F=Y(L,l,e)*L%e,ke=Y(F,a,e)*E%e,re=Y(ke,r,e)*f%e,ge=Y(re,s,e)*B%e,be=Y(ge,n,e)*c%e,ne=Y(be,Yt,e);if(!yt.eql(yt.sqr(ne),t))throw new Error("Cannot find square root");return ne}var yt=Ue(gt.p,{sqrt:Zo}),Ne=nn(gt,{Fp:yt,endo:$o});var on={};function mt(t,...e){let r=on[t];if(r===void 0){let n=Ze(Dr(t));r=fe(n,n),on[t]=r}return Ze(fe(r,...e))}var Kt=t=>t.toBytes(!0).slice(1),Xt=t=>t%Yt===Go;function Wt(t){let{Fn:e,BASE:r}=Ne,n=e.fromBytes(t),o=r.multiply(n);return{scalar:Xt(o.y)?n:e.neg(n),bytes:Kt(o)}}function an(t){let e=yt;if(!e.isValidNot0(t))throw new Error("invalid x: Fail if x \u2265 p");let r=e.create(t*t),n=e.create(r*t+BigInt(7)),o=e.sqrt(n);Xt(o)||(o=e.neg(o));let i=Ne.fromAffine({x:t,y:o});return i.assertValidity(),i}var Xe=Oe;function cn(...t){return Ne.Fn.create(Xe(mt("BIP0340/challenge",...t)))}function sn(t){return Wt(t).bytes}function Yo(t,e,r=_e(32)){let{Fn:n}=Ne,o=D(t,void 0,"message"),{bytes:i,scalar:s}=Wt(e),a=D(r,32,"auxRand"),l=n.toBytes(s^Xe(mt("BIP0340/aux",a))),c=mt("BIP0340/nonce",l,i,o),{bytes:f,scalar:u}=Wt(c),m=cn(f,i,o),h=new Uint8Array(64);if(h.set(f,0),h.set(n.toBytes(n.create(u+m*s)),32),!ln(h,o,i))throw new Error("sign: Invalid signature produced");return h}function ln(t,e,r){let{Fp:n,Fn:o,BASE:i}=Ne,s=D(t,64,"signature"),a=D(e,void 0,"message"),l=D(r,32,"publicKey");try{let c=an(Xe(l)),f=Xe(s.subarray(0,32));if(!n.isValidNot0(f))return!1;let u=Xe(s.subarray(32,64));if(!o.isValidNot0(u))return!1;let m=cn(o.toBytes(f),Kt(c),a),h=i.multiplyUnsafe(u).add(c.multiplyUnsafe(o.neg(m))),{x:B,y:E}=h.toAffine();return!(h.is0()||!Xt(E)||B!==f)}catch{return!1}}var Jt=(()=>{let r=(n=_e(48))=>Yr(n,gt.n);return{keygen:Zt(r,sn),getPublicKey:sn,sign:Yo,verify:ln,Point:Ne,utils:{randomSecretKey:r,taggedHash:mt,lift_x:an,pointToBytes:Kt},lengths:{secretKey:32,publicKey:32,publicKeyHasPrefix:!1,signature:64,seed:48}}})();p();var xn=ze(bn()),wn;(function(t){t[t.DEBUG=0]="DEBUG",t[t.INFO=1]="INFO",t[t.WARN=2]="WARN",t[t.ERROR=3]="ERROR"})(wn||(wn={}));var he=(0,xn.default)({name:"nostr-crypto-utils",level:x.env.LOG_LEVEL||"info",transport:void 0,formatters:{level:t=>({level:t.toUpperCase()}),log:t=>{if(t&&typeof t=="object"&&"err"in t){let e={...t};if(e.err instanceof Error){let r=e.err;e.err={message:r.message,stack:r.stack,name:r.name}}return e}return t}}});p();var hi=async()=>{if(typeof window<"u"&&window.crypto)return window.crypto;if(typeof globalThis<"u"&&globalThis.crypto)return globalThis.crypto;try{let t=await Promise.resolve().then(()=>ze(or()));if(t.webcrypto)return t.webcrypto}catch{he.debug("Node crypto not available")}throw new Error("No WebCrypto implementation available")},ir=class{cryptoInstance=null;initPromise;constructor(){this.initPromise=this.initialize()}async initialize(){this.cryptoInstance=await hi()}async ensureInitialized(){if(await this.initPromise,!this.cryptoInstance)throw new Error("Crypto implementation not initialized");return this.cryptoInstance}async getSubtle(){return(await this.ensureInitialized()).subtle}async getRandomValues(e){return(await this.ensureInitialized()).getRandomValues(e)}},ic=new ir,yi=Jt.sign,mi=Jt.verify;p();p();p();p();p();var wi=async()=>{if(typeof window<"u"&&window.crypto)return window.crypto;if(typeof globalThis<"u"&&globalThis.crypto)return globalThis.crypto;try{let t=await Promise.resolve().then(()=>ze(or()));if(t.webcrypto)return t.webcrypto}catch{he.debug("Node crypto not available")}throw new Error("No WebCrypto implementation available")},sr=class{cryptoInstance=null;initPromise;constructor(){this.initPromise=this.initialize()}async initialize(){this.cryptoInstance=await wi()}async ensureInitialized(){if(await this.initPromise,!this.cryptoInstance)throw new Error("Crypto implementation not initialized");return this.cryptoInstance}async getSubtle(){return(await this.ensureInitialized()).subtle}async getRandomValues(e){return(await this.ensureInitialized()).getRandomValues(e)}},Tc=new sr;p();p();var ns=ze(In()),os=ze(Gn());p();p();var zc=new TextEncoder,$c=new TextDecoder;p();p();p();function Zn(t){try{return Or(t.trim().toLowerCase(),Ur)}catch{return!1}}var Yn=6,G=Z.storage.local,ps=[new URL("wss://relay.damus.io"),new URL("wss://relay.primal.net"),new URL("wss://relay.snort.social"),new URL("wss://relay.getalby.com/v1"),new URL("wss://nos.lol")];async function Kn(){await Wn("profileIndex",0),await Wn("profiles",[await Jn()]);let t=(await G.get({version:0})).version;for(;t<Yn;)t=await hs(t,Yn),await G.set({version:t})}async function hs(t,e){if(t===0){let r=await me();return r.forEach(n=>n.hosts={}),await G.set({profiles:r}),t+1}if(t===1){let r=await me();return await G.set({profiles:r}),t+1}if(t===2){let r=await me();return r.forEach(n=>n.relayReminder=!0),await G.set({profiles:r}),t+1}if(t===3)return(await G.get({isEncrypted:!1})).isEncrypted||await G.set({isEncrypted:!1}),t+1;if(t===4){let r=await me();return r.forEach(n=>{n.type||(n.type="local"),n.bunkerUrl===void 0&&(n.bunkerUrl=null),n.remotePubkey===void 0&&(n.remotePubkey=null)}),await G.set({profiles:r}),t+1}if(t===5){let r=Math.floor(Date.now()/1e3),n=await me();return n.forEach(o=>{o.updatedAt===void 0&&(o.updatedAt=r)}),await G.set({profiles:n,platformSyncEnabled:!0}),t+1}}async function me(){return(await G.get({profiles:[]})).profiles}async function Xn(){return(await me()).map(e=>e.name)}async function ys(){return await Z.runtime.sendMessage({kind:"generatePrivateKey"})}async function Jn(t="Default Nostr Profile",e="local"){return{name:t,privKey:e==="local"?await ys():"",hosts:{},relays:ps.map(r=>({url:r.href,read:!0,write:!0})),relayReminder:!1,type:e,bunkerUrl:null,remotePubkey:null,updatedAt:Math.floor(Date.now()/1e3)}}async function Wn(t,e){let r=(await G.get(t))[t];return r==null||r==null?(await G.set({[t]:e}),e):r}async function Qn(t,e){let r=await me();r[t].name=e,r[t].updatedAt=Math.floor(Date.now()/1e3),await G.set({profiles:r})}async function eo(t,e){await Z.runtime.sendMessage({kind:"savePrivateKey",payload:[t,e]})}async function to(){let t=await me(),e=await Jn("New Profile");return t.push(e),await G.set({profiles:t}),t.length-1}function ro(t){let e=/^[\da-f]{64}$/i.test(t),r=/^nsec1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{58}$/.test(t);return e||r||ms(t)||Zn(t)}function ms(t){return/^ncryptsec1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]+$/.test(t)}var b={profiles:[],selectedIndex:null,nsecVisible:!1,nsecValue:"",npubValue:"",showImport:!1,importData:"",importName:"",importError:"",toast:""};function C(t){return document.getElementById(t)}function gs(t){return!t||t.length<=20?t||"":t.slice(0,12)+"\u2026"+t.slice(-8)}function At(t){b.toast=t,te(),setTimeout(()=>{b.toast="",te()},2e3)}function bs(t){let e=document.createElement("div");return e.textContent=t,e.innerHTML}function te(){let t=C("profile-list"),e=C("no-profiles"),r=C("profile-count"),n=C("detail-empty"),o=C("detail-panel"),i=C("import-panel");r&&(r.textContent=b.profiles.length+" profile"+(b.profiles.length!==1?"s":"")),t&&(t.innerHTML=b.profiles.map(f=>`
            <div class="profile-item ${b.selectedIndex===f.index?"selected":""}" data-profile-index="${f.index}">
                <div class="font-bold text-sm truncate" style="color:#f8f8f2;">${bs(f.name)}</div>
                <div class="profile-npub">${gs(f.npub)}</div>
            </div>
        `).join(""),t.querySelectorAll("[data-profile-index]").forEach(f=>{f.addEventListener("click",()=>oo(parseInt(f.dataset.profileIndex,10)))})),e&&(e.style.display=b.profiles.length===0?"block":"none");let s=b.selectedIndex!==null&&!b.showImport,a=b.showImport,l=!s&&!a;if(n&&(n.style.display=l?"block":"none"),o&&(o.style.display=s?"block":"none"),i&&(i.style.display=a?"block":"none"),s){let f=b.profiles.find(E=>E.index===b.selectedIndex),u=C("detail-name"),m=C("detail-npub"),h=C("detail-nsec"),B=C("toggle-nsec-btn");u&&(u.textContent=f?f.name:""),m&&(m.textContent=b.npubValue||""),h&&(h.textContent=b.nsecVisible?b.nsecValue:"\u2022".repeat(24)),B&&(B.textContent=b.nsecVisible?"Hide":"Reveal")}if(a){let f=C("import-data"),u=C("import-name"),m=C("import-error");f&&document.activeElement!==f&&(f.value=b.importData),u&&document.activeElement!==u&&(u.value=b.importName),m&&(m.textContent=b.importError,m.style.display=b.importError?"block":"none")}let c=C("toast");c&&(c.textContent=b.toast,c.style.display=b.toast?"block":"none")}async function no(){let t=await Xn(),e=[];for(let r=0;r<t.length;r++){let n="";try{n=await Z.runtime.sendMessage({kind:"getNpub",payload:r})}catch{}e.push({index:r,name:t[r],npub:n||""})}b.profiles=e}async function oo(t){b.selectedIndex=t,b.nsecVisible=!1,b.nsecValue="",b.npubValue="",b.showImport=!1;let e=b.profiles.find(r=>r.index===t);b.npubValue=e?e.npub:"";try{let r=await Z.runtime.sendMessage({kind:"getNsec",payload:t});b.nsecValue=r||""}catch{b.nsecValue=""}te()}function ws(){b.nsecVisible=!b.nsecVisible,te()}async function xs(){b.npubValue&&(await navigator.clipboard.writeText(b.npubValue),At("nPub copied"))}async function Es(){b.nsecValue&&(await navigator.clipboard.writeText(b.nsecValue),At("nSec copied"),setTimeout(()=>{navigator.clipboard.writeText("").catch(()=>{})},3e4))}async function vs(){if(b.selectedIndex===null)return;let t=b.profiles.find(i=>i.index===b.selectedIndex);if(!t)return;let e={name:t.name,npub:b.npubValue,nsec:b.nsecValue,exportedAt:new Date().toISOString(),source:"NostrKey"},r=new Blob([JSON.stringify(e,null,2)],{type:"application/json"}),n=URL.createObjectURL(r),o=document.createElement("a");o.href=n,o.download=`nostrkey-${t.name.replace(/[^a-zA-Z0-9_-]/g,"_")}.json`,o.click(),URL.revokeObjectURL(n),At("Exported")}function Bs(){b.showImport=!0,b.selectedIndex=null,b.importData="",b.importName="",b.importError="",te()}function As(){b.showImport=!1,b.importData="",b.importName="",b.importError="",te()}async function Is(){b.importError="";let t=b.importData.trim();if(!t){b.importError="Please paste a JSON object or nsec string.",te();return}let e=b.importName.trim(),r="";try{let n=JSON.parse(t);r=n.nsec||n.privkey||n.privateKey||"",!e&&n.name&&(e=n.name)}catch{r=t}if(!r){b.importError='No private key found. Provide an nsec string or JSON with an "nsec" field.',te();return}if(!ro(r)){b.importError="Invalid key format. Expected nsec1..., hex private key, or seed phrase.",te();return}e||(e="Imported Profile");try{let n=await to();await Qn(n,e),await eo(n,r),await no(),b.showImport=!1,b.importData="",b.importName="",b.importError="",await oo(n),At('Imported "'+e+'"')}catch(n){b.importError="Import failed: "+(n.message||"unknown error"),te()}}function ks(){C("close-btn")?.addEventListener("click",()=>window.close()),C("copy-npub-btn")?.addEventListener("click",xs),C("copy-nsec-btn")?.addEventListener("click",Es),C("toggle-nsec-btn")?.addEventListener("click",ws),C("export-btn")?.addEventListener("click",vs),C("import-btn")?.addEventListener("click",Bs),C("cancel-import-btn")?.addEventListener("click",As),C("do-import-btn")?.addEventListener("click",Is),C("import-data")?.addEventListener("input",t=>{b.importData=t.target.value}),C("import-name")?.addEventListener("input",t=>{b.importName=t.target.value})}async function Ss(){await Kn();let t=await Z.runtime.sendMessage({kind:"isEncrypted"}),e=C("vault-locked-gate"),r=C("vault-main-content");if(!t){e&&(e.style.display="block"),r&&(r.style.display="none"),C("gate-security-btn")?.addEventListener("click",()=>{let n=Z.runtime.getURL("security/security.html");window.open(n,"nostrkey-options")});return}e&&(e.style.display="none"),r&&(r.style.display="block"),await no(),ks(),te()}document.addEventListener("DOMContentLoaded",Ss);})();
/*! Bundled license information:

ieee754/index.js:
  (*! ieee754. BSD-3-Clause License. Feross Aboukhadijeh <https://feross.org/opensource> *)

buffer/index.js:
  (*!
   * The buffer module from node.js, for the browser.
   *
   * @author   Feross Aboukhadijeh <https://feross.org>
   * @license  MIT
   *)

@noble/hashes/utils.js:
  (*! noble-hashes - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/base/index.js:
  (*! scure-base - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/bip39/index.js:
  (*! scure-bip39 - MIT License (c) 2022 Patricio Palladino, Paul Miller (paulmillr.com) *)

@noble/curves/utils.js:
@noble/curves/abstract/modular.js:
@noble/curves/abstract/curve.js:
@noble/curves/abstract/weierstrass.js:
@noble/curves/secp256k1.js:
  (*! noble-curves - MIT License (c) 2022 Paul Miller (paulmillr.com) *)
*/
