(()=>{var t=typeof browser<"u"?browser:typeof chrome<"u"?chrome:null;if(!t)throw new Error("browser-polyfill: No extension API namespace found (neither browser nor chrome).");var n=typeof browser>"u"&&typeof chrome<"u";function o(e,a){return(...s)=>{try{let r=a.apply(e,s);if(r&&typeof r.then=="function")return r}catch{}return new Promise((r,u)=>{a.apply(e,[...s,(...c)=>{t.runtime&&t.runtime.lastError?u(new Error(t.runtime.lastError.message)):r(c.length<=1?c[0]:c)}])})}}var i={};i.runtime={sendMessage(...e){return n?o(t.runtime,t.runtime.sendMessage)(...e):t.runtime.sendMessage(...e)},onMessage:t.runtime.onMessage,getURL(e){return t.runtime.getURL(e)},openOptionsPage(){return n?o(t.runtime,t.runtime.openOptionsPage)():t.runtime.openOptionsPage()},get id(){return t.runtime.id}};i.storage={local:{get(...e){return n?o(t.storage.local,t.storage.local.get)(...e):t.storage.local.get(...e)},set(...e){return n?o(t.storage.local,t.storage.local.set)(...e):t.storage.local.set(...e)},clear(...e){return n?o(t.storage.local,t.storage.local.clear)(...e):t.storage.local.clear(...e)},remove(...e){return n?o(t.storage.local,t.storage.local.remove)(...e):t.storage.local.remove(...e)}}};i.tabs={create(...e){return n?o(t.tabs,t.tabs.create)(...e):t.tabs.create(...e)},query(...e){return n?o(t.tabs,t.tabs.query)(...e):t.tabs.query(...e)},remove(...e){return n?o(t.tabs,t.tabs.remove)(...e):t.tabs.remove(...e)},update(...e){return n?o(t.tabs,t.tabs.update)(...e):t.tabs.update(...e)},get(...e){return n?o(t.tabs,t.tabs.get)(...e):t.tabs.get(...e)},getCurrent(...e){return n?o(t.tabs,t.tabs.getCurrent)(...e):t.tabs.getCurrent(...e)}};var d=[["none","NIP-XX: None","Reserved for the future use."]],l=[];function m(){let e=document.getElementById("features-container");e&&(e.innerHTML=l.map(([a,s,r,u])=>`
        <div class="mt-4">
            <input
                class="checkbox"
                type="checkbox"
                id="${a}"
                ${s?"checked":""}
                data-feature="${a}"
            />
            <label for="${a}" class="font-bold">${r}</label>
            <p class="italic">${u}</p>
        </div>
    `).join(""),e.querySelectorAll('input[type="checkbox"]').forEach(a=>{a.addEventListener("change",async s=>{let r=s.target.dataset.feature,u=s.target.checked;await i.storage.local.set({[r]:u}),await f()})}))}async function f(){l=await Promise.all(d.map(async([e,a,s])=>{let r=`feature:${e}`,u=await i.storage.local.get({[r]:!1});return u=u[r],[r,u,a,s]})),m()}async function p(){await f()}document.addEventListener("DOMContentLoaded",p);document.getElementById("close-btn")?.addEventListener("click",()=>{window.close()});})();
