(()=>{var e=typeof browser<"u"?browser:typeof chrome<"u"?chrome:null;if(!e)throw new Error("browser-polyfill: No extension API namespace found (neither browser nor chrome).");var r=typeof browser>"u"&&typeof chrome<"u";function n(t,o){return(...a)=>{try{let s=o.apply(t,a);if(s&&typeof s.then=="function")return s}catch{}return new Promise((s,u)=>{o.apply(t,[...a,(...i)=>{e.runtime&&e.runtime.lastError?u(new Error(e.runtime.lastError.message)):s(i.length<=1?i[0]:i)}])})}}var c={};c.runtime={sendMessage(...t){return r?n(e.runtime,e.runtime.sendMessage)(...t):e.runtime.sendMessage(...t)},onMessage:e.runtime.onMessage,getURL(t){return e.runtime.getURL(t)},openOptionsPage(){return r?n(e.runtime,e.runtime.openOptionsPage)():e.runtime.openOptionsPage()},get id(){return e.runtime.id}};c.storage={local:{get(...t){return r?n(e.storage.local,e.storage.local.get)(...t):e.storage.local.get(...t)},set(...t){return r?n(e.storage.local,e.storage.local.set)(...t):e.storage.local.set(...t)},clear(...t){return r?n(e.storage.local,e.storage.local.clear)(...t):e.storage.local.clear(...t)},remove(...t){return r?n(e.storage.local,e.storage.local.remove)(...t):e.storage.local.remove(...t)}},sync:e.storage?.sync?{get(...t){return r?n(e.storage.sync,e.storage.sync.get)(...t):e.storage.sync.get(...t)},set(...t){return r?n(e.storage.sync,e.storage.sync.set)(...t):e.storage.sync.set(...t)},remove(...t){return r?n(e.storage.sync,e.storage.sync.remove)(...t):e.storage.sync.remove(...t)},clear(...t){return r?n(e.storage.sync,e.storage.sync.clear)(...t):e.storage.sync.clear(...t)},getBytesInUse(...t){return e.storage.sync.getBytesInUse?r?n(e.storage.sync,e.storage.sync.getBytesInUse)(...t):e.storage.sync.getBytesInUse(...t):Promise.resolve(0)}}:null,onChanged:e.storage?.onChanged||null};c.tabs={create(...t){return r?n(e.tabs,e.tabs.create)(...t):e.tabs.create(...t)},query(...t){return r?n(e.tabs,e.tabs.query)(...t):e.tabs.query(...t)},remove(...t){return r?n(e.tabs,e.tabs.remove)(...t):e.tabs.remove(...t)},update(...t){return r?n(e.tabs,e.tabs.update)(...t):e.tabs.update(...t)},get(...t){return r?n(e.tabs,e.tabs.get)(...t):e.tabs.get(...t)},getCurrent(...t){return r?n(e.tabs,e.tabs.getCurrent)(...t):e.tabs.getCurrent(...t)},sendMessage(...t){return r?n(e.tabs,e.tabs.sendMessage)(...t):e.tabs.sendMessage(...t)}};var d=[["none","NIP-XX: None","Reserved for the future use."]],l=[];function y(){let t=document.getElementById("features-container");t&&(t.innerHTML=l.map(([o,a,s,u])=>`
        <div class="mt-4">
            <input
                class="checkbox"
                type="checkbox"
                id="${o}"
                ${a?"checked":""}
                data-feature="${o}"
            />
            <label for="${o}" class="font-bold">${s}</label>
            <p class="italic">${u}</p>
        </div>
    `).join(""),t.querySelectorAll('input[type="checkbox"]').forEach(o=>{o.addEventListener("change",async a=>{let s=a.target.dataset.feature,u=a.target.checked;await c.storage.local.set({[s]:u}),await f()})}))}async function f(){l=await Promise.all(d.map(async([t,o,a])=>{let s=`feature:${t}`,u=await c.storage.local.get({[s]:!1});return u=u[s],[s,u,o,a]})),y()}async function m(){await f()}document.addEventListener("DOMContentLoaded",m);document.getElementById("close-btn")?.addEventListener("click",()=>{window.close()});})();
