(()=>{var e=typeof browser<"u"?browser:typeof chrome<"u"?chrome:null;if(!e)throw new Error("browser-polyfill: No extension API namespace found (neither browser nor chrome).");var r=typeof browser>"u"&&typeof chrome<"u";function n(t,s){return(...o)=>{try{let a=s.apply(t,o);if(a&&typeof a.then=="function")return a}catch{}return new Promise((a,u)=>{s.apply(t,[...o,(...l)=>{e.runtime&&e.runtime.lastError?u(new Error(e.runtime.lastError.message)):a(l.length<=1?l[0]:l)}])})}}var c={};c.runtime={sendMessage(...t){return r?n(e.runtime,e.runtime.sendMessage)(...t):e.runtime.sendMessage(...t)},onMessage:e.runtime.onMessage,getURL(t){return e.runtime.getURL(t)},openOptionsPage(){return r?n(e.runtime,e.runtime.openOptionsPage)():e.runtime.openOptionsPage()},get id(){return e.runtime.id}};c.storage={local:{get(...t){return r?n(e.storage.local,e.storage.local.get)(...t):e.storage.local.get(...t)},set(...t){return r?n(e.storage.local,e.storage.local.set)(...t):e.storage.local.set(...t)},clear(...t){return r?n(e.storage.local,e.storage.local.clear)(...t):e.storage.local.clear(...t)},remove(...t){return r?n(e.storage.local,e.storage.local.remove)(...t):e.storage.local.remove(...t)}},sync:e.storage?.sync?{get(...t){return r?n(e.storage.sync,e.storage.sync.get)(...t):e.storage.sync.get(...t)},set(...t){return r?n(e.storage.sync,e.storage.sync.set)(...t):e.storage.sync.set(...t)},remove(...t){return r?n(e.storage.sync,e.storage.sync.remove)(...t):e.storage.sync.remove(...t)},clear(...t){return r?n(e.storage.sync,e.storage.sync.clear)(...t):e.storage.sync.clear(...t)},getBytesInUse(...t){return e.storage.sync.getBytesInUse?r?n(e.storage.sync,e.storage.sync.getBytesInUse)(...t):e.storage.sync.getBytesInUse(...t):Promise.resolve(0)}}:null,onChanged:e.storage?.onChanged||null};c.tabs={create(...t){return r?n(e.tabs,e.tabs.create)(...t):e.tabs.create(...t)},query(...t){return r?n(e.tabs,e.tabs.query)(...t):e.tabs.query(...t)},remove(...t){return r?n(e.tabs,e.tabs.remove)(...t):e.tabs.remove(...t)},update(...t){return r?n(e.tabs,e.tabs.update)(...t):e.tabs.update(...t)},get(...t){return r?n(e.tabs,e.tabs.get)(...t):e.tabs.get(...t)},getCurrent(...t){return r?n(e.tabs,e.tabs.getCurrent)(...t):e.tabs.getCurrent(...t)},sendMessage(...t){return r?n(e.tabs,e.tabs.sendMessage)(...t):e.tabs.sendMessage(...t)}};c.alarms=e.alarms?{create(...t){let s=e.alarms.create(...t);return s&&typeof s.then=="function"?s:Promise.resolve()},clear(...t){return r?n(e.alarms,e.alarms.clear)(...t):e.alarms.clear(...t)},onAlarm:e.alarms.onAlarm}:null;var m=[["none","NIP-XX: None","Reserved for the future use."]],i=[];function d(){let t=document.getElementById("features-container");t&&(t.innerHTML=i.map(([s,o,a,u])=>`
        <div class="mt-4">
            <input
                class="checkbox"
                type="checkbox"
                id="${s}"
                ${o?"checked":""}
                data-feature="${s}"
            />
            <label for="${s}" class="font-bold">${a}</label>
            <p class="italic">${u}</p>
        </div>
    `).join(""),t.querySelectorAll('input[type="checkbox"]').forEach(s=>{s.addEventListener("change",async o=>{let a=o.target.dataset.feature,u=o.target.checked;await c.storage.local.set({[a]:u}),await f()})}))}async function f(){i=await Promise.all(m.map(async([t,s,o])=>{let a=`feature:${t}`,u=await c.storage.local.get({[a]:!1});return u=u[a],[a,u,s,o]})),d()}async function y(){await f()}document.addEventListener("DOMContentLoaded",y);document.getElementById("close-btn")?.addEventListener("click",()=>{window.close()});})();
